<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1061114927;

$Parameters = array( "name" => "intranet",
                     "summary" => "Intranet site",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => false,
                     "extension" => false,
                     "ezpublish" => array( "version" => "3.2.0-1",
                                           "named-version" => "3.2 beta1" ),
                     "maintainers" => array( array( "name" => "Anonymous User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead",
                                                    "modified" => "1061280124" ) ),
                     "packaging" => array( "timestamp" => "1061280124",
                                           "host" => "bf.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1061280124" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1061280124",
                                                  "person" => "Anonymous User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package" ),
                                                  "release" => "1",
                                                  "modified" => "1061280124" ) ),
                     "file-list" => array( "default" => array( array( "name" => false,
                                                                      "subdirectory" => false,
                                                                      "type" => "design",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => false,
                                                                      "path" => false,
                                                                      "file-type" => false,
                                                                      "design" => "intranet",
                                                                      "copy-file" => false,
                                                                      "modified" => "1061280125",
                                                                      "md5" => false ),
                                                               array( "name" => "override.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "intranet",
                                                                      "variable-name" => "user_siteaccess",
                                                                      "path" => "settings/siteaccess/intranet/override.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061280126",
                                                                      "md5" => "ee6c2358f777a184ad76ef4249535e25" ),
                                                               array( "name" => "site.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "intranet",
                                                                      "variable-name" => "user_siteaccess",
                                                                      "path" => "settings/siteaccess/intranet/site.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061280126",
                                                                      "md5" => "6dd4ea0e347357128d08e4eed06a0f68" ),
                                                               array( "name" => "override.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "admin",
                                                                      "variable-name" => "admin_siteaccess",
                                                                      "path" => "settings/siteaccess/admin/override.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061280127",
                                                                      "md5" => "50f4805254652ccea3c0191a23ce5c21" ),
                                                               array( "name" => "site.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "admin",
                                                                      "variable-name" => "admin_siteaccess",
                                                                      "path" => "settings/siteaccess/admin/site.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061280127",
                                                                      "md5" => "275939f14d668221e40aca876209892f" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => false,
                                                                      "path" => "intranetthumbnail.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061280130",
                                                                      "md5" => "80ab419e64e12e27a592913a7e4a1a86" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1061280125" ) ),
                                              "requires" => array( array( "type" => "ezdb",
                                                                          "name" => "mysql",
                                                                          "value" => false,
                                                                          "modified" => "1061280128" ),
                                                                   array( "type" => "ezdb",
                                                                          "name" => "postgresql",
                                                                          "value" => false,
                                                                          "modified" => "1061280129" ),
                                                                   array( "type" => "ezdb",
                                                                          "name" => "postgresql",
                                                                          "value" => false,
                                                                          "modified" => "1061280130" ) ),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1061280125",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ),
                                         array( "path" => "packages/intranet.sql",
                                                "database-type" => "mysql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061280128",
                                                "os" => false,
                                                "filename" => "intranet.sql",
                                                "sub-directory" => false ),
                                         array( "path" => "kernel/sql/postgresql/kernel_schema.sql",
                                                "database-type" => "postgresql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061280129",
                                                "os" => false,
                                                "filename" => "kernel_schema.sql",
                                                "sub-directory" => false ),
                                         array( "path" => "kernel/sql/postgresql/cleandata.sql",
                                                "database-type" => "postgresql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061280130",
                                                "os" => false,
                                                "filename" => "cleandata.sql",
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1061280125",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1061280124",
                             "version-number" => "1061280124",
                             "release-number" => "1061280124",
                             "licence" => "1061280124",
                             "state" => "1061280124",
                             "summary" => 1061280131 );
$RepositoryPath = "packages";
?>
