{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'Default value'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>
    {section show=eq( $class_attribute.data_int1, 1 )}
        {'Current date'|i18n( 'design/standard/class/datatype' )}
    {section-else}
        <i>{'Empty'|i18n( 'design/standard/class/datatype' )}</i>
    {/section}
    </p>
</div>
