{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let content=$class_attribute.content}
<div class="element">
<label>{'Selection method'|i18n( 'design/standard/class/datatype' )}</label><div class="labelbreak"></div>
    <p>{$content.selection_type|choose( 'None'|i18n( 'design/standard/class/datatype' ),
                                        'Dropdown list'|i18n( 'design/standard/class/datatype' ),
                                        'List with radio buttons'|i18n( 'design/standard/class/datatype' ),
                                        'List with Check boxes'|i18n( 'design/standard/class/datatype' ),
                                        'Multiple selection list'|i18n( 'design/standard/class/datatype' ),
                                        'Template based, multi'|i18n( 'design/standard/class/datatype' ),
                                        'Template based, single'|i18n( 'design/standard/class/datatype' ),

                                         )}</p>
</div>

<div class="element">
<label>{'Default selection node'|i18n( 'design/standard/class/datatype' )}</label><div class="labelbreak"></div>
{section show=$content.default_selection_node}
    {let selection_node=fetch( content, node, hash( node_id, $content.default_selection_node ) )}
    <p>{'Selecting from %nodename'|i18n( 'design/standard/class/datatype',, hash( '%nodename', $selection_node.name ) )}</p>
    {/let}
{/section}

<div class="element">
<label>{'Filter class'|i18n( 'design/standard/class/datatype' )}</label><div class="labelbreak"></div>
{section show=$content.filter_class}
    {let filter_class=fetch( content, class, hash( class_id, $content.filter_class ) )}
    <p>{$filter_class.name}</p>
    {/let}
{/section}

<div class="element">
<label>{'Default placement node'|i18n( 'design/standard/class/datatype' )}</label><div class="labelbreak"></div>
{section show=$content.default_placement_node}
    {let default_placement_node=fetch( content, node, hash( node_id, $content.default_placement_node ) )}
    <p>{'Placing new objects under %nodename'|i18n( 'design/standard/class/datatype',, hash( '%nodename', $default_placement_node.name ) )}</p>
    {/let}
{/section}

{*
<p>
{section show=$content.fuzzy_match}
    {'Allow fuzzy match'|i18n( 'design/standard/class/datatype' )}
{section-else}
    {'Do not allow fuzzy match'|i18n( 'design/standard/class/datatype' )}
{/section}
</p>
*}
</div>

{/let}
