{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* Style. *}
<div class="block">
<label>{'Style'|i18n( 'design/standard/class/datatype' )}:</label>
<p>
{if $class_attribute.data_int1}
    {'Multiple choice'|i18n( 'design/standard/class/datatype' )}
{else}
    {'Single choice'|i18n( 'design/standard/class/datatype' )}
{/if}
</p>
</div>

{* Interface. *}
<div class="block">
<label>{'Interface'|i18n( 'design/standard/class/datatype' )}:</label>
<p>
{if $class_attribute.data_int2}
    {'Drop-down menu / multi select'|i18n( 'design/standard/class/datatype' )}
{else}
    {'Radio buttons / checkboxes'|i18n( 'design/standard/class/datatype' )}
{/if}
</p>
</div>

{* Elements. *}
<div class="block">
<label>{'Elements'|i18n( 'design/standard/class/datatype' )}:</label>
{section show=$class_attribute.content.enum_list}
<table class="list" cellspacing="0">
<tr>
    <th>{'Element'|i18n( 'design/standard/class/datatype' )}</th>
    <th>{'Value'|i18n( 'design/standard/class/datatype' )}</th>
</tr>
{section var=Elements loop=$class_attribute.content.enum_list sequence=array( bglight, bgdark )}
<tr class="{$Elements.sequence}">
    <td>{$Elements.item.enumelement|wash}</td>
    <td>{$Elements.item.enumvalue|wash}</td>
</tr>
{/section}
</table>
{section-else}
<p>{'There are no elements in the list.'|i18n( 'design/standard/class/datatype' )}</p>
{/section}
</div>
