{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<label>{"Max file size"|i18n("design/standard/class/datatype")}</label><div class="labelbreak"></div>
<p>{$class_attribute.data_int1}&nbsp;MB</p>
