{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'Default value'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_int3}</p>
</div>


{switch name=input_state match=$class_attribute.data_int4}

{* Only min value is set. *}
{case match=1}
<div class="block">
    <div class="element">
        <label>{'Min integer value'|i18n( 'design/standard/class/datatype' )}:</label>
        <p>{$class_attribute.data_int1}</p>
    </div>

    <div class="element">
        <label>{'Max integer value'|i18n( 'design/standard/class/datatype' )}:</label>
        <p><i>{'Empty'|i18n( 'design/standard/class/datatype' )}</i></p>
    </div>

    <div class="break"></div>
</div>
{/case}

{* Only max value is set. *}
{case match=2}
<div class="block">
    <div class="element">
        <label>{'Min integer value'|i18n( 'design/standard/class/datatype' )}:</label>
        <p><i>{'Empty'|i18n( 'design/standard/class/datatype' )}</i></p>
    </div>

    <div class="element">
        <label>{'Max integer value'|i18n( 'design/standard/class/datatype' )}:</label>
        <p>{$class_attribute.data_int2}</p>
    </div>

    <div class="break"></div>
</div>
{/case}

{* Both values are set. *}
{case match=3}
<div class="block">
    <div class="element">
        <label>{'Min integer value'|i18n( 'design/standard/class/datatype' )}:</label>
        <p>{$class_attribute.data_int1}</p>
    </div>

    <div class="element">
        <label>{'Max integer value'|i18n( 'design/standard/class/datatype' )}:</label>
        <p>{$class_attribute.data_int2}</p>
    </div>

    <div class="break"></div>
</div>
{/case}

{* None of the values are set. *}
{case}
<div class="block">
    <div class="element">
        <label>{'Min integer value'|i18n( 'design/standard/class/datatype' )}:</label>
        <p><i>{'Empty'|i18n( 'design/standard/class/datatype' )}</i></p>
    </div>

    <div class="element">
        <label>{'Max integer value'|i18n( 'design/standard/class/datatype' )}:</label>
        <p><i>{'Empty'|i18n( 'design/standard/class/datatype' )}</i></p>
    </div>

    <div class="break"></div>
</div>
{/case}

{/switch}
