{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* Default number of rows. *}
<div class="block">
    <label>{'Default number of rows'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_int1}</p>
</div>

{* Columns. *}
<div class="block">
<label>{'Columns'|i18n( 'design/standard/class/datatype' )}:</label>
{section show=$class_attribute.content.columns}
<table class="list" cellspacing="0">
<tr>
    <th>{'Matrix column'|i18n( 'design/standard/class/datatype' )}</th>
    <th>{'Identifier'|i18n( 'design/standard/class/datatype' )}</th>
</tr>
{section var=Columns loop=$class_attribute.content.columns sequence=array( bglight, bgdark )}
<tr class="{$Columns.sequence}">
    <td>{$Columns.item.name|wash}</td>
    <td>{$Columns.item.identifier|wash}</td>
</tr>
{/section}
</table>
{section-else}
<p>
{'The matrix does not have any columns.'|i18n( 'design/standard/class/datatype' )}
</p>
{/section}
</div>
