{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'VAT'|i18n( 'design/standard/class/datatype' )}:</label>
    {if eq( $class_attribute.data_int1, 1 )}{'Price inc. VAT'|i18n( 'design/standard/class/datatype' )}{/if}
    {if eq( $class_attribute.data_int1, 2 )}{'Price ex. VAT'|i18n( 'design/standard/class/datatype' )}{/if}
</div>

<div class="block">
<label>{'VAT type'|i18n( 'design/standard/class/datatype' )}:</label>
{include uri='design:shop/vattype/view.tpl' vat_types=$class_attribute.content.vat_type current_val=$class_attribute.data_float1}
</div>
