{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="maincontentheader">

<div class="message-warning">
{switch match=$error_number}
{case match=1}
<h3>
{"The section < %1 > was not assigned to the nodes listed below because of insufficient permission:"|i18n( 'design/admin/section/assign_notification', '', hash( '%1', $section_name ) )}
</h3><p>
{foreach $denied_node_list as $node}
{delimiter}<br />{/delimiter}
 - {$node.name}
{/foreach}</p>
{/case}
{case match=2}
<h3>
{"There are no objects in the system that you could assign the section < %1 > to."|i18n( 'design/admin/section/assign_notification', '', hash( '%1', $section_name ) )}
</h3>
{/case}
{case match=3}
<h3>
{"You do not have permission to assign the section < %1 > to any object."|i18n( 'design/admin/section/assign_notification', '', hash( '%1', $section_name ) )}
<h3/>
{/case}
{/switch}
</h3>
</div>

</div>

<form action={"/section/list"|ezurl} method="post">
<div class="buttonblock">
    <input class="button" type="submit" value="{'OK'|i18n( 'design/admin/section/assign_notification' )}" />
</div>
</form>

