<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "corporate_green",
                     "development" => false,
                     "summary" => "Green design for corporate",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => "sitestyle",
                     "extension" => false,
                     "is_installed" => false,
                     "is_active" => true,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "3.3.0-1",
                                           "named-version" => "3.3 beta 1" ),
                     "maintainers" => array(),
                     "packaging" => array( "timestamp" => "1069864041",
                                           "host" => "jb.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1069864041" ) ),
                     "groups" => array(),
                     "changelog" => array(),
                     "file-list" => array( "default" => array( array( "name" => "corporate-green.css",
                                                                      "subdirectory" => "design/corporate/stylesheets",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "cssfile",
                                                                      "path" => "design/corporate/stylesheets/corporate-green.css",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864041",
                                                                      "md5" => "82025d10016b59db7f3597086cb99a10" ),
                                                               array( "name" => "sidebar-background.gif",
                                                                      "subdirectory" => "design/corporate/images",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/corporate/images/sidebar-background.gif",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864042",
                                                                      "md5" => "ee3bc2992eb5f2058baad88259ad3acb" ),
                                                               array( "name" => "header_image-green.jpg",
                                                                      "subdirectory" => "design/corporate/images",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/corporate/images/header_image-green.jpg",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864042",
                                                                      "md5" => "b93149b27cd885031e6c3ef9b2d3e549" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "design/corporate/images/corporate-green.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => true,
                                                                      "modified" => 1069864042,
                                                                      "md5" => "df523c84220c42c50dba770b938ee5d4" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1069864041" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1069864041",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1069864041",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1069864041",
                             "summary" => "1069864041",
                             "type" => "1069864041",
                             "version-number" => "1069864041",
                             "release-number" => "1069864041",
                             "licence" => "1069864041",
                             "state" => "1069864041" );
$InstallData = array();
$RepositoryPath = "var/corporate/storage/packages";
?>
