{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* Default value. *}
<div class="block">
    <label>{'Default value'|i18n( 'design/standard/class/datatype' )}:</label>
    <select name="ContentClass_ezdatetime_default_{$class_attribute.id}">
    <option value="0" {section show=eq( $class_attribute.data_int1, 0 )}selected="selected"{/section}>{'Empty'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="1" {section show=eq( $class_attribute.data_int1, 1 )}selected="selected"{/section}>{'Current datetime'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="2" {section show=eq( $class_attribute.data_int1, 2 )}selected="selected"{/section}>{'Adjusted current datetime'|i18n( 'design/standard/class/datatype' )}</option>
    </select>
</div>

{* Custom default value. *}
<div class="block">
<fieldset>
    <legend>{'Current date and time adjusted by'|i18n( 'design/standard/class/datatype' )}</legend>

    <div class="block">
    {* Year. *}
    <div class="element">
        <label>{'Year'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezdatetime_year_{$class_attribute.id}" size="5" value="{section show=$class_attribute.content.year}{$class_attribute.content.year}{/section}" />
    </div>

    {* Month. *}
    <div class="element">
        <label>{'Month'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezdatetime_month_{$class_attribute.id}" size="3" value="{section show=$class_attribute.content.month}{$class_attribute.content.month}{/section}" />
    </div>

    {* Day. *}
    <div class="element">
        <label>{'Day'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezdatetime_day_{$class_attribute.id}" size="3" value="{section show=$class_attribute.content.day}{$class_attribute.content.day}{/section}" />
        &nbsp;
        &nbsp;
        &nbsp;
    </div>

    {* Hour. *}
    <div class="element">
        <label>{'Hour'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezdatetime_hour_{$class_attribute.id}" size="3" value="{section show=$class_attribute.content.hour}{$class_attribute.content.hour}{/section}" />
    </div>

    {* Minute. *}
    <div class="element">
        <label>{'Minute'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezdatetime_minute_{$class_attribute.id}" size="3" value="{section show=$class_attribute.content.minute}{$class_attribute.content.minute}{/section}" />
    </div>

    <div class="break"></div>

</div>
</fieldset>
</div>
