{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* Multiple choice. *}
<div class="block">
    <label>{'Multiple choice'|i18n( 'design/standard/class/datatype' )}:</label>
    <input type="checkbox" name="ContentClass_ezenum_ismultiple_value_{$class_attribute.id}" value="{$class_attribute.data_int1}" {if $class_attribute.data_int1}checked="checked"{/if} />
</div>

{* Checkbox style. *}
<div class="block">
<label>{'Style'|i18n( 'design/standard/class/datatype' )}:</label>
<select name="ContentClass_ezenum_isoption_value_{$class_attribute.id}">
<option value="0" {if eq( $class_attribute.data_int2, '0' )}selected="selected"{/if}>{'Checkboxes / radio buttons'|i18n( 'design/standard/class/datatype' )}</option>
<option value="1" {if eq( $class_attribute.data_int2, '1' )}selected="selected"{/if}>{'Drop-down menu / multi menu'|i18n( 'design/standard/class/datatype' )}</option>
</select>
</div>

<div class="block">
<fieldset>
<legend>{'Elements'|i18n( 'design/standard/class/datatype' )}</legend>
{section show=$class_attribute.content.enum_list}
<table class="list" cellspacing="0">

<tr>
<th class="tight">&nbsp;</th>
<th>{'Element'|i18n( 'design/standard/class/datatype' )}</th>
<th>{'Value'|i18n( 'design/standard/class/datatype' )}</th>
</tr>

{section var=Enums loop=$class_attribute.content.enum_list sequence=array( bglight,bgdark )}
<tr>

    {* Remove. *}
    <td>
    <input type="checkbox" name="ContentClass_data_enumremove_{$class_attribute.id}[]" value="{$Enums.item.id}" title="{'Select element for removal.'}" />
    </td>

    {* Element. *}
    <td>
    <input class="box" type="text" name="ContentClass_data_enumelement_{$class_attribute.id}[]" value="{$Enums.item.enumelement|wash}" size="10" maxlength="255" />
    </td>

    {* Value. *}
    <td>
    <input class="box" type="text" name="ContentClass_data_enumvalue_{$class_attribute.id}[]" value="{$Enums.item.enumvalue|wash}" size="10" maxlength="255" />
    <input type="hidden" name="ContentClass_data_enumid_{$class_attribute.id}[]" value="{$Enums.item.id}" />
    </td>

</tr>
{/section}
</table>
{section-else}
<p>{'There are no elements in the list.'|i18n( 'design/standard/class/datatype' )}</p>
{/section}

{if $class_attribute.content.enum_list}
<input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_remove_selected]" value="{'Remove selected'|i18n('design/standard/class/datatype')}" title="{'Remove selected elements.'|i18n( 'design/standard/class/datatype' )}" />
{else}
<input class="button-disabled" type="submit" name="CustomActionButton[{$class_attribute.id}_remove_selected]" value="{'Remove selected'|i18n('design/standard/class/datatype')}" disabled="disabled" />
{/if}

<input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_new_enumelement]" value="{'New element'|i18n('design/standard/class/datatype')}" title="{'Add a new enum element.'|i18n( 'design/standard/class/datatype' )}"  />
</fieldset>
</div>