{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let content=$class_attribute.content}
{* <div class="element">
<input type="checkbox" name="ContentClass_ezenhancedselection_ismultiple_value_{$class_attribute.id}" {section show=$class_attribute.data_int1}checked{/section} /><label>{"Multiple choice"|i18n("design/standard/class/datatype")}</label>
<div class="labelbreak"></div>
*}
<div class="element">
<label>{'Selection method'|i18n( 'design/standard/class/datatype' )}</label><div class="labelbreak"></div>

<select name="ContentClass_ezobjectrelation_selection_type_{$class_attribute.id}">
    <option value="4" {eq( $content.selection_type, 4 )|choose( '', 'selected="selected"' )}>{'Multiple selection list'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="5" {eq( $content.selection_type, 5 )|choose( '', 'selected="selected"' )}>{'Template based, multi'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="6" {eq( $content.selection_type, 6 )|choose( '', 'selected="selected"' )}>{'Template based, single'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="3" {eq( $content.selection_type, 3 )|choose( '', 'selected="selected"' )}>{'List with Check boxes'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="2" {eq( $content.selection_type, 2 )|choose( '', 'selected="selected"' )}>{'List with radio buttons'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="1" {eq( $content.selection_type, 1 )|choose( '', 'selected="selected"' )}>{'Dropdown list'|i18n( 'design/standard/class/datatype' )}</option>
{*    <option value="0" {eq( $content.selection_type, 0 )|choose( '', 'selected="selected"' )}>{'Browse'|i18n( 'design/standard/class/datatype' )}</option>*}
</select>
</div>

<div class="block">
<fieldset>
<legend>{'Default selection node'|i18n( 'design/standard/class/datatype')}</legend>
{section show=$content.default_selection_node}
    {let selection_node=fetch( content, node, hash( node_id, $content.default_selection_node ) )}
    <p>{'Selecting from %nodename'|i18n( 'design/standard/class/datatype',, hash( '%nodename', $selection_node.name ) )}</p>
    {/let}
    <input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_disable_selection_node]" value="{'Remove selection'|i18n('design/standard/class/datatype')}" />
{section-else}
{/section}
<input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_browse_for_selection_node]" value="{'Select node'|i18n('design/standard/class/datatype')}" />
</fieldset>
</div>
<div class="block">
<fieldset>
<legend>Class</legend>
<select name="ContentClass_ezobjectrelation_filter_class_{$class_attribute.id}">

{let classes=fetch( 'class', 'list' )}
<option value="" {eq( $content.filter_class, "" )|choose( '', 'selected="selected"' )}>{'(none)'|i18n('design/standard/class/datatype')}</option>

{section loop=$:classes}
    <option value="{$:item.id}" {eq( $content.filter_class, $:item.id )|choose( '', 'selected="selected"' )}>{$:item.name}</option>
{/section}
{/let}
</select>

</fieldset>
</div>

<div class="block">
<fieldset>
<legend>{'New Objects'|i18n( 'design/standard/class/datatype' )}</legend>
<label>{'Allow Creation of new objects'|i18n( 'design/standard/class/datatype')}</label>

<label>{'Default placement node'|i18n('design/standard/class/datatype')}</label>
{section show=$content.default_placement_node}
    {let placement_node=fetch( content, node, hash( node_id, $content.default_placement_node ) )}
    <p>{'Placing new objects under %nodename'|i18n( 'design/standard/class/datatype',, hash( '%nodename', $placement_node.name ) )}</p>
    <input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_remove_placement_node]" value="{'Remove default placement node'|i18n('design/standard/class/datatype')}" />
    {/let}
{section-else}
{/section}
<input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_browse_for_placement_node]" value="{'Select node'|i18n('design/standard/class/datatype')}" />
</fieldset>
</div>


{/let}
