{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
<label>{'Default name'|i18n( 'design/standard/class/datatype' )}:</label>
<input class="box" type="text" name="ContentClass_ezrangeoption_default_name_{$class_attribute.id}" value="{$class_attribute.data_text1|wash}" size="30" maxlength="60" />
</div>
