{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* Default value. *}
<div class="block">
    <label>{'Default value'|i18n( 'design/standard/class/datatype' )}:</label>
    <input class="box" type="text" name="ContentClass_ezstring_default_value_{$class_attribute.id}" value="{$class_attribute.data_text1|wash}" size="30" maxlength="50" />
</div>

{* Maximum string length. *}
<div class="block">
    <label>{'Max string length'|i18n( 'design/standard/class/datatype' )}:</label>
    <input type="text" name="ContentClass_ezstring_max_string_length_{$class_attribute.id}" value="{$class_attribute.data_int1}" size="5" maxlength="5" />&nbsp;{'characters'|i18n( 'design/standard/class/datatype' )}
</div>

{* Trim input *}
<div class="block">
    <label>{'Trim white spaces left and right'|i18n( 'design/standard/class/datatype' )}:</label>
    <input
            type="checkbox"
            name="ContentClass_ezstring_trim_{$class_attribute.id}"
            value="1"
            {if $class_attribute.data_int2}
                checked="checked"
            {/if}
    />
</div>
