{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
   <div class="element">
    <label>{'Preferred number of rows'|i18n( 'design/standard/class/datatype' )}:</label>
    <select name="ContentClass_ezxmltext_cols_{$class_attribute.id}">
        <option value="2"  {if eq( $class_attribute.data_int1,  2 )}selected="selected"{/if}>2</option>
        <option value="5"  {if eq( $class_attribute.data_int1,  5 )}selected="selected"{/if}>5</option>
        <option value="10" {if eq( $class_attribute.data_int1, 10 )}selected="selected"{/if}>10</option>
        <option value="15" {if eq( $class_attribute.data_int1, 15 )}selected="selected"{/if}>15</option>
        <option value="20" {if eq( $class_attribute.data_int1, 20 )}selected="selected"{/if}>20</option>
        <option value="25" {if eq( $class_attribute.data_int1, 25 )}selected="selected"{/if}>25</option>
    </select>
    </div>

    <div class="element">
    <label>{'Tag preset'|i18n( 'design/standard/class/datatype' )}:</label>
    <select name="ContentClass_ezxmltext_tagpreset_{$class_attribute.id}">
    {def $tag_preset_list = ezini( 'TagSettings', 'TagPresets', 'ezxml.ini' )}
        <option value="">{'Default'|i18n( 'design/standard/content/datatype' )}</option>
        {foreach $tag_preset_list as $presetKey => $presetName}
            <option value="{$presetKey|wash()}"{if eq( $presetKey, $class_attribute.data_text2 )} selected="selected"{/if}>{$presetName|wash()}</option>
        {/foreach}
    {undef $tag_preset_list}
    </select>
    </div>
</div>