{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="object-{$object_parameters.align}{section show=ne($classification|trim,'')} {$classification|wash}{/section}"{section show=is_set($id)} id="{$id}"{/section}>
{$object.name|wash} - {"You do not have permission to view this object"|i18n( 'design/admin/node/view/embed'  )}.
</div>