{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{$object.name|wash} - {"You do not have sufficient permissions to view this object"|i18n( 'design/admin/node/view/embed'  )}.

{*
Set variable to true if the object should be rendered as a block
tag. If it should be rendered as inline use false.*}
{set-block scope=root variable=is_block}false{/set-block}
{*
*}
