{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div{if and(is_set( $align ), $align )} class="object-{$align}"{/if}>
<table bgcolor="#eeeeee">
<tr>
    <td>
    {$content}
    </td>
</tr>
</table>
</div>