{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if ne( $classification, 'html' )}
<pre{if ne($classification|trim,'')} class="{$classification|wash}"{/if}>{$content|wash(xhtml)}</pre>
{else}
{$content}
{/if}
