<h1>Page setup</h1>

<p>
In eZ publish every page is generated dynamically. The main idea with the pages in
eZ publish is that the content, code, internationalisation and design are separated.
Every page is therefore generated by a template. In the template you can decide where
the content should be placed and the layout of the site.
</p>

<p>
eZ publish is component based, so there are several templates that make up the page you
see. The main template in eZ publish, pagelayout.tpl, normally defines the menus and
basic layout of the site. You then have an area in this template where the actual content
is shown, this can be e.g. an article, a list of articles or an image. If you e.g. show a list
of articles in the main area there are several templates that make up this list.
</p>

<h2>View modes</h2>

<p>
In eZ publish you can view content of different classes. Examples include article, product and forum
messages. These objects can also be viewed in different ways. The two most common view modes are
line and full. The line view mode is normally used in lists and full is used when viewing an object,
for instance an article.
</p>

<p>
For more information about how to customize eZ publish visit the
<a href={"/sdk"|ezurl}>SDK documentation</a>
and read the tutorials on the subject.
</p>
