#!/bin/bash
EXTENSION_NAME="eZ Online Editor"
EXTENSION_IDENTIFIER="ezoe"
EXTENSION_SUMMARY="eZ Publish Online Editor for XML fields."
EXTENSION_LICENSE="GNU General Public License v2.0"
EXTENSION_VERSION="5.1.0Alpha1"
EXTENSION_PUBLISH_VERSION="4.1 and higher"
EXTENSION_ARCHIVE_NAME="ezoe"
EXTENSION_PHP_VERSION="5.2"


EXTENSION_FILTER_FILES="INSTALL FAQ"
