<?php

class eZMailTest extends ezpTestCase
{
    public static function providerTestValidate()
    {
        return array(
            array( 'kc@ez.no',      1 ),
            array( 'kc+list@ez.no', 1 ),
            array( "kc'@ez.no",     1 ),
            array( "k..c'@ez.no",   0 ),
            array( ".kc@ez.no",     0 ),

            array( 'johndoe@example.com', 1 ),
            array( 'johndoe@example.org', 1 ),
            array( 'johndoe@example.gov', 1 ),
            array( 'johndoe@example.biz', 1 ),
            array( 'johndoe@example.net', 1 ),
            array( 'johndoe@example.mil', 1 ),
            array( 'johndoe@example.xxx', 1 ),
            array( 'johndoe@example.info', 1 ),
            array( 'johndoe@example.aero', 1 ),
            array( 'johndoe@example.jobs', 1 ),
            array( 'johndoe@example.name', 1 ),
            array( 'johndoe@example.museum', 1 ),
            array( 'johndoe@example.solarspace', 1 ),
            array( 'johndoe@example.co.uk', 1 ),
            array( 'johndoe@e.x.a.m.p.l.e.com', 1 ),
            array( 'johndoe@e-x-a-m-p-l-e.com', 1 ),
            array( 'johndoe@e.x-a.m-p.l-e.com', 1 ),
            array( 'johndoe@example.xx', 1 ),
            array( 'johndoe@-example.com', 1 ),
            array( 'johndoe@example-.com', 1 ),
            array( 'johndoe@1example.com', 1 ),
            array( 'johndoe@example.c-m', 1 ),
            array( 'johndoe@1.aa', 1 ),

            // doma'in part as IP address
            array( 'johndoe@0.0.0.0', 1 ),
            array( 'johndoe@11.11.11.11', 1 ),
            array( 'johndoe@111.111.111.111', 1 ),
            array( 'johndoe@127.0.0.1', 1 ),
            array( 'johndoe@[127.0.0.1]', 1 ),
            array( 'johndoe@1.12.123.1', 1 ),
            array( 'johndoe@255.255.255.255', 1 ),

            array( 'a@example.com', 1 ),
            array( 'A@example.com', 1 ),
            array( '1@example.com', 1 ),

            array( '+@example.com', 1 ),
            array( '*@example.com', 1 ),
            array( '{@example.com', 1 ),
            array( '}@example.com', 1 ),
            array( '|@example.com', 1 ),
            array( '~@example.com', 1 ),
            array( '/@example.com', 1 ),
            array( '\'@example.com', 1 ),
            array( '-@example.com', 1 ),
            array( '_@example.com', 1 ),
            array( '`@example.com', 1 ),
            array( '^@example.com', 1 ),
            array( '$@example.com', 1 ),
            array( '%@example.com', 1 ),
            array( '&@example.com', 1 ),
            array( '!@example.com', 1 ),

            array( 'john+doe@example.com', 1 ),
            array( 'john*doe@example.com', 1 ),
            array( 'john{doe@example.com', 1 ),
            array( 'john}doe@example.com', 1 ),
            array( 'john|doe@example.com', 1 ),
            array( 'john~doe@example.com', 1 ),
            array( 'john/doe@example.com', 1 ),
            array( 'john\'doe@example.com', 1 ),
            array( 'john-doe@example.com', 1 ),
            array( 'john_doe@example.com', 1 ),
            array( 'john`doe@example.com', 1 ),
            array( 'john^doe@example.com', 1 ),
            array( 'john$doe@example.com', 1 ),
            array( 'john%doe@example.com', 1 ),
            array( 'john&doe@example.com', 1 ),
            array( 'john!doe@example.com', 1 ),

            array( 'johndoe+@example.com', 1 ),
            array( 'johndoe*@example.com', 1 ),
            array( 'johndoe{@example.com', 1 ),
            array( 'johndoe}@example.com', 1 ),
            array( 'johndoe|@example.com', 1 ),
            array( 'johndoe~@example.com', 1 ),
            array( 'johndoe/@example.com', 1 ),
            array( 'johndoe\'@example.com', 1 ),
            array( 'johndoe-@example.com', 1 ),
            array( 'johndoe_@example.com', 1 ),
            array( 'johndoe`@example.com', 1 ),
            array( 'johndoe^@example.com', 1 ),
            array( 'johndoe$@example.com', 1 ),
            array( 'johndoe%@example.com', 1 ),
            array( 'johndoe&@example.com', 1 ),
            array( 'johndoe!@example.com', 1 ),

            array( 'j.o.h.n.d.o.e@example.com', 1 ),
            array( 'john-doe@example.com', 1 ),
            array( 'j-o-h-n-d-o-e@example.com', 1 ),
            array( 'j._-oh.n---d.__--o.___---e@example.com', 1 ),
            array( 'john_doe@example.com', 1 ),
            array( 'john/doe@example.com', 1 ),
            array( 'j_o_h_n_d_o_e@example.com', 1 ),
            array( 'j.o_h-n.d_o-e@example.com', 1 ),
            array( 'johndoe1@example.com', 1 ),
            array( 'j1o2h3n4d5o6e7@example.com', 1 ),
            array( 'j1.o2_h3-n4.d5_o6-e7@example.com', 1 ),
            array( '1johndoe@example.com', 1 ),
            array( '+1~1+@example.com', 1 ),
            array( '{johndoe}@example.com', 1 ),
            array( '{_johndoe_}@example.com', 1 ),
            array( '|johndoe|@example.com', 1 ),
            array( '-johndoe-@example.com', 1 ),
            array( '`johndoe`@example.com', 1 ),
            array( '\'johndoe\'@example.com', 1 ),
            array( '"[[ johndoe ]]"@example.com', 1 ),
            array( '"john.\'doe\'"@example.com', 1 ),

            array( '"john doe"@example.com', 1 ),
            array( '"john\doe"@example.com', 1 ),
            array( '"john?doe"@example.com', 1 ),
            array( '"john,doe"@example.com', 1 ),
            array( '"john@doe"@example.com', 1 ),
            array( '"john=doe"@example.com', 1 ),
            array( '"john<doe"@example.com', 1 ),
            array( '"john>doe"@example.com', 1 ),
            array( '"john;doe"@example.com', 1 ),
            array( '"john:doe"@example.com', 1 ),
            array( '"john¢doe"@example.com', 1 ),
            array( '"john±doe"@example.com', 1 ),
            array( '"john³doe"@example.com', 1 ),
            array( '"johnµdoe"@example.com', 1 ),
            array( '"john¶doe"@example.com', 1 ),
            array( '"john·doe"@example.com', 1 ),
            array( '"john¸doe"@example.com', 1 ),
            array( '"john¹doe"@example.com', 1 ),
            array( '"john°doe"@example.com', 1 ),
            array( '"john½doe"@example.com', 1 ),
            array( '"john»doe"@example.com', 1 ),
            array( '"john§doe"@example.com', 1 ),
            array( '"john®doe"@example.com', 1 ),
            array( '"john¯doe"@example.com', 1 ),
            array( '"john¬doe"@example.com', 1 ),
            array( '"john¼doe"@example.com', 1 ),
            array( '"johnþdoe"@example.com', 1 ),
            array( '"john¡doe"@example.com', 1 ),
            array( '"john£doe"@example.com', 1 ),
            array( '"john¤doe"@example.com', 1 ),
            array( '"john¥doe"@example.com', 1 ),
            array( '"johnÞdoe"@example.com', 1 ),
            array( '"john¦doe"@example.com', 1 ),
            array( '"johnªdoe"@example.com', 1 ),
            array( '"john¨doe"@example.com', 1 ),
            array( '"john©doe"@example.com', 1 ),
            array( '"john¿doe"@example.com', 1 ),
            array( '"john¾doe"@example.com', 1 ),
            array( '"john¼doe"@example.com', 1 ),
            array( '"john«doe"@example.com', 1 ),

            // incorrect addresses
            array( 'name', 0 ),
            array( 'johndoe', 0 ),
            array( 'johndoe@', 0 ),
            array( 'johndoe@.', 0 ),
            array( 'johndoe@a.a', 0 ),
            array( 'johndoe@1.a', 0 ),
            array( 'johndoe@example', 0 ),
            array( 'johndoe@example.x', 0 ),
            array( 'johndoe@example.0', 0 ),
            array( 'johndoe@example.00', 0 ),
            array( 'johndoe@example.000', 0 ),
            array( 'johndoe@example,com', 0 ),
            array( 'johndoe@e$ample.com', 0 ),
            array( 'johndoe@e!ample.com', 0 ),
            array( 'johndoe@e?ample.com', 0 ),
            array( 'johndoe@e\'ample.com', 0 ),
            array( 'johndoe@e"ample.com', 0 ),
            array( 'johndoe@e^ample.com', 0 ),
            array( 'johndoe@e%ample.com', 0 ),
            array( 'johndoe@e~ample.com', 0 ),
            array( 'johndoe@e`ample.com', 0 ),
            array( 'johndoe@examp|e.com', 0 ),
            array( 'johndoe@e#ample.com', 0 ),
            array( 'johndoe@e ample.com', 0 ),
            array( 'johndoe@e_ample.com', 0 ),
            array( 'johndoe@e%20ample.com', 0 ),
            array( 'johndoe@example.c m', 0 ),
            array( 'johndoe@{example}.com', 0 ),
            array( 'johndoe@(example).com', 0 ),
            array( 'johndoe@[example].com', 0 ),
            array( 'johndoe@"example".com', 0 ),
            array( 'johndoe@\'example\'.com', 0 ),
            array( 'johndoe@example.$$$', 0 ),
            array( 'johndoe@example.!!!', 0 ),
            array( 'johndoe@example.???', 0 ),
            array( 'johndoe@example.###', 0 ),
            array( 'johndoe@example....', 0 ),
            array( 'johndoe@example.,,,', 0 ),
            array( 'johndoe@example.[]', 0 ),
            array( 'johndoe@example.{}', 0 ),
            array( 'johndoe@example.()', 0 ),
            array( 'johndoe@example.""', 0 ),
            array( 'johndoe@example.\'\'', 0 ),
            array( 'johndoe@example.||', 0 ),
            array( 'johndoe@`example.com', 0 ),
            array( 'johndoe@|example.com', 0 ),
            array( 'johndoe@,example.com', 0 ),
            array( 'johndoe@.example.com', 0 ),
            array( '@', 0 ),
            array( '@.', 0 ),

            // domain part as IP address
            array( 'johndoe@1111.111.11.1', 0 ),
            array( 'johndoe@256.256.256.256', 0 ),
            array( 'johndoe@FF.0F.FF.7A', 0 ),
            array( 'johndoe@1-7.0.0.1', 0 ),
            array( 'johndoe@127.0.0.[1]', 0 ),
            array( 'johndoe@(127.0.0.1)', 0 ),
            array( 'johndoe@{127.0.0.1}    ', 0 ),
            array( 'johndoe@"127.0.0.1"', 0 ),
            array( 'johndoe@\'127.0.0.1\'', 0 ),
            array( 'johndoe@|127.0.0.1|', 0 ),
            array( 'johndoe@`127.0.0.1`', 0 ),
            array( 'johndoe@127.0.0', 0 ),
            array( 'johndoe@127.0', 0 ),
            array( 'johndoe@127', 0 ),
            array( 'johndoe@0.00', 0 ),

            // localpart
            array( 'example.com', 0 ),
            array( '@example.com', 0 ),

            array( '.@example.com', 0 ),
            array( ',@example.com', 0 ),
            array( '\@example.com', 0 ),
            array( '"@example.com', 0 ),
            array( '=@example.com', 0 ),
            array( '?@example.com', 0 ),
            array( '<@example.com', 0 ),
            array( '>@example.com', 0 ),
            array( ':@example.com', 0 ),
            array( ';@example.com', 0 ),
            array( '¢@example.com', 0 ),
            array( '±@example.com', 0 ),
            array( '³@example.com', 0 ),
            array( 'µ@example.com', 0 ),
            array( '¶@example.com', 0 ),
            array( '·@example.com', 0 ),
            array( '¸@example.com', 0 ),
            array( '¹@example.com', 0 ),
            array( '°@example.com', 0 ),
            array( '½@example.com', 0 ),
            array( '»@example.com', 0 ),
            array( '§@example.com', 0 ),
            array( '®@example.com', 0 ),
            array( '¯@example.com', 0 ),
            array( '¬@example.com', 0 ),
            array( '¼@example.com', 0 ),
            array( 'þ@example.com', 0 ),
            array( '¡@example.com', 0 ),
            array( '£@example.com', 0 ),
            array( '¤@example.com', 0 ),
            array( '¥@example.com', 0 ),
            array( 'Þ@example.com', 0 ),
            array( '¦@example.com', 0 ),
            array( 'ª@example.com', 0 ),
            array( '¨@example.com', 0 ),
            array( '©@example.com', 0 ),
            array( '¿@example.com', 0 ),
            array( '¾@example.com', 0 ),
            array( '¼@example.com', 0 ),
            array( '«@example.com', 0 ),

            array( '.johndoe@example.com', 0 ),
            array( 'johndoe.@example.com', 0 ),
            array( 'johndoe,@example.com', 0 ),
            array( 'johndoe\@example.com', 0 ),
            array( 'johndoe"@example.com', 0 ),
            array( 'johndoe=@example.com', 0 ),
            array( 'johndoe?@example.com', 0 ),
            array( 'johndoe<@example.com', 0 ),
            array( 'johndoe>@example.com', 0 ),
            array( 'johndoe:@example.com', 0 ),
            array( 'johndoe;@example.com', 0 ),
            array( 'johndoe¢@example.com', 0 ),
            array( 'johndoe±@example.com', 0 ),
            array( 'johndoe³@example.com', 0 ),
            array( 'johndoeµ@example.com', 0 ),
            array( 'johndoe¶@example.com', 0 ),
            array( 'johndoe·@example.com', 0 ),
            array( 'johndoe¸@example.com', 0 ),
            array( 'johndoe¹@example.com', 0 ),
            array( 'johndoe°@example.com', 0 ),
            array( 'johndoe½@example.com', 0 ),
            array( 'johndoe»@example.com', 0 ),
            array( 'johndoe§@example.com', 0 ),
            array( 'johndoe®@example.com', 0 ),
            array( 'johndoe¯@example.com', 0 ),
            array( 'johndoe¬@example.com', 0 ),
            array( 'johndoe¼@example.com', 0 ),
            array( 'johndoeþ@example.com', 0 ),
            array( 'johndoe¡@example.com', 0 ),
            array( 'johndoe£@example.com', 0 ),
            array( 'johndoe¤@example.com', 0 ),
            array( 'johndoe¥@example.com', 0 ),
            array( 'johndoeÞ@example.com', 0 ),
            array( 'johndoe¦@example.com', 0 ),
            array( 'johndoeª@example.com', 0 ),
            array( 'johndoe¨@example.com', 0 ),
            array( 'johndoe©@example.com', 0 ),
            array( 'johndoe¿@example.com', 0 ),
            array( 'johndoe¾@example.com', 0 ),
            array( 'johndoe¼@example.com', 0 ),
            array( 'johndoe«@example.com', 0 ),
            array( 'john doe@example.com', 0 ),

            array( 'john,doe@example.com', 0 ),
            array( 'john"doe@example.com', 0 ),
            array( 'john@doe@example.com', 0 ),
            array( 'john\doe@example.com', 0 ),
            array( 'john=doe@example.com', 0 ),
            array( 'john?doe@example.com', 0 ),
            array( 'john<doe@example.com', 0 ),
            array( 'john>doe@example.com', 0 ),
            array( 'john;doe@example.com', 0 ),
            array( 'john:doe@example.com', 0 ),
            array( 'john¢doe@example.com', 0 ),
            array( 'john±doe@example.com', 0 ),
            array( 'john³doe@example.com', 0 ),
            array( 'johnµdoe@example.com', 0 ),
            array( 'john¶doe@example.com', 0 ),
            array( 'john·doe@example.com', 0 ),
            array( 'john¸doe@example.com', 0 ),
            array( 'john¹doe@example.com', 0 ),
            array( 'john°doe@example.com', 0 ),
            array( 'john½doe@example.com', 0 ),
            array( 'john»doe@example.com', 0 ),
            array( 'john§doe@example.com', 0 ),
            array( 'john®doe@example.com', 0 ),
            array( 'john¯doe@example.com', 0 ),
            array( 'john¬doe@example.com', 0 ),
            array( 'john¼doe@example.com', 0 ),
            array( 'johnþdoe@example.com', 0 ),
            array( 'john¡doe@example.com', 0 ),
            array( 'john£doe@example.com', 0 ),
            array( 'john¤doe@example.com', 0 ),
            array( 'john¥doe@example.com', 0 ),
            array( 'johnÞdoe@example.com', 0 ),
            array( 'john¦doe@example.com', 0 ),
            array( 'johnªdoe@example.com', 0 ),
            array( 'john¨doe@example.com', 0 ),
            array( 'john©doe@example.com', 0 ),
            array( 'john¿doe@example.com', 0 ),
            array( 'john¾doe@example.com', 0 ),
            array( 'john¼doe@example.com', 0 ),
            array( 'john«doe@example.com', 0 ),

            array( '- johndoe -@example.com', 0 ),
            array( '[johndoe]@example.com', 0 ),
            array( '(johndoe)@example.com', 0 ),
            array( '<johndoe>@example.com', 0 ),
        );
    }

    public static function providerTestExtractEmail()
    {
        return array(
                        array( 'John Doe <jdoe+subaddr@test.example.com>', 'John Doe', 'jdoe+subaddr@test.example.com' ),
                        array( 'John Doe <jdoe@test.example.com>', 'John Doe', 'jdoe@test.example.com' ),
                        array( 'John Doe <jdoe@example.com>', 'John Doe', 'jdoe@example.com' ),
                        array( '豆豆龍 <jdoe@example.com>', '豆豆龍', 'jdoe@example.com' ),
                        array( '小丁噹 <"小丁噹"@example.com>', '小丁噹', '"小丁噹"@example.com' ),
                    );
    }

    public static function providerTestStripEmail()
    {
        return array(
                        array( 'Bla bla bla bla "楊大葶" <user@example.com>  test test <anotheruser@example.com> test', 'user@example.com' ),
                        array( 'Bla bla bla bla "楊大葶"@example.com test <anotheruser@example.com> test test', '"楊大葶"@example.com' ),
                        array( 'Bla bla bla bla John Doe <jdoe+subaddr@test.example.com> test <anotheruser@example.com> test test', 'jdoe+subaddr@test.example.com' ),
                    );
    }

    /**
     * @dataProvider providerTestValidate
     */
    public function testValidate( $email, $valid )
    {
        $this->assertEquals( $valid, eZMail::validate( $email ) );
    }

    /**
     * @dataProvider providerTestExtractEmail
     */
    public function testExtractEmail( $recipient, $name, $email )
    {
        eZMail::extractEmail( $recipient, $extractedEmail, $extractedName );
        self::assertEquals( $extractedEmail, $email );
        self::assertEquals( $extractedName, $name );
    }

    /**
     * @dataProvider providerTestStripEmail
     */
    public function testStripEmail( $text, $firstEmailAddress )
    {
    }
}

?>