{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="element">
{let selectedSections=$event.selected_sections}
{"Sections"|i18n("design/standard/workflow/eventtype/view")}:

{section show=$selectedSections|contains(-1)}
{"Any"|i18n("design/standard/workflow/eventtype/view")}
{section-else}

{let comma=false()}
{section var=section loop=$event.workflow_type.sections}
{section show=$selectedSections|contains($section.value)}
{section show=$comma}, {/section}
{$section.Name|wash}
{set comma=true()}
{/section}
{/section}
{/let}

{/section}

{/let} 
</div>



<div class="element">
{let selectedClasses=$event.selected_classes}
{"Classes to run workflow"|i18n("design/standard/workflow/eventtype/view")}:

{section show=$selectedClasses|contains(-1)}
{"Any"|i18n("design/standard/workflow/eventtype/view")}
{section-else}

{let comma=false()}
{section var=class loop=$event.workflow_type.contentclass_list}
{section show=$selectedClasses|contains($class.value)}
{section show=$comma}, {/section}
{$class.Name|wash}
{set comma=true()}
{/section}
{/section}
{/let}

{/section}

{/let} 
</div>



<div class="element">
{let selectedGroups=$event.selected_usergroups}
{"Users without workflow IDs"|i18n("design/standard/workflow/eventtype/view")}:

{let comma=false()}
{section var=user loop=$event.workflow_type.usergroups}
{section show=$selectedGroups|contains($user.value)}
{section show=$comma}, {/section}
{$user.Name|wash}
{set comma=true()}
{/section}
{/section}
{/let}

{/let}
</div>



<div class="element">
{let selectedWorkflow=$event.selected_workflow}
{"Workflow to run"|i18n("design/standard/workflow/eventtype/view")}:

{section var=workflow loop=$event.workflow_type.workflow_list}
{section show=$selectedWorkflow|contains($workflow.value)}
{$workflow.Name|wash}
{/section}
{/section}

{/let}
</div>
