{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="element">
{"Approver users"|i18n("design/standard/workflow/eventtype/view")}:

{section var=user loop=$event.approve_users}
    {delimiter}, {/delimiter}
    {fetch( content, object, hash( object_id, $user.item ) ).name|wash}
{/section}
</div>

<div class="element">
{"Approver groups"|i18n("design/standard/workflow/eventtype/view")}:

{section var=user loop=$event.approve_groups}
    {delimiter}, {/delimiter}
    {fetch( content, object, hash( object_id, $user.item ) ).name|wash}
{/section}
</div>

<div class="element">
{"Sections"|i18n("design/standard/workflow/eventtype/view")}:

{section show=$event.selected_sections|contains(-1)}
    {"Any"|i18n("design/standard/workflow/eventtype/view")}
{section-else}
    {section var=section loop=$event.selected_sections}
        {delimiter}, {/delimiter}
        {fetch( 'section', 'object', hash( 'section_id',$section.item ) ).name|wash}
    {/section}
{/section}
</div>

<div class="element">
{"Users without approval"|i18n("design/standard/workflow/eventtype/view")}:

{section var=group loop=$event.selected_usergroups}
    {delimiter}, {/delimiter}
    {fetch( content, object, hash( object_id, $group.item ) ).name|wash}
{/section}
</div>

<div class="element">
{"Language"|i18n("design/standard/workflow/eventtype/view")}:

{if eq( count( $event.language_list ), 0 )}
    {"Any"|i18n( "design/standard/workflow/eventtype/view" )}
{else}
    {section var=language loop=$event.language_list}
        {delimiter}, {/delimiter}
    {$language|wash}
    {/section}
{/if}
</div>

<div class="element">
{'Affected versions'|i18n( 'design/admin/workflow/eventtype/edit' )}:
{if or( lt($event.version_option, 1), gt($event.version_option, 2) )}&nbsp;{'All versions'|i18n( 'design/admin/workflow/eventtype/edit' )}
{elseif eq( $event.version_option, 1)}&nbsp;{'Publishing new object'|i18n( 'design/admin/workflow/eventtype/edit' )}
{elseif eq( $event.version_option, 2)}&nbsp;{'Updating existing object'|i18n( 'design/admin/workflow/eventtype/edit' )}
{else}&nbsp;-&nbsp;{/if}
</div>
