{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{section show=$first}
<ul>
{/section}
<li class="toolbar-item {$placement}">
<div class="toolbox">
    <div class="toolbox-design">
        <div class="toolbox-content">
            <a href={$url|ezurl}><div class="setup-icon"><img src={$link_icon|ezimage} alt={$title|wash} /></div><div class="setup-title">{$title|wash}</div></a>
        </div>
    </div>
</div>
</li>
{section show=$last}
</ul>
{/section}
