{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form method="post" action={"design/toolbarlist"|ezurl}>

<div class="context-block">

{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">

<h1 class="context-title">{'Toolbar management'|i18n( 'design/standard/design/toolbar' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

<label>{'Siteaccess'|i18n( 'design/standard/design/toolbar' )}:</label>

    {if $current_siteaccess}
{*        <p>{'Current siteaccess'|i18n( 'design/standard/design/toolbar' )}: <strong>{$current_siteaccess}</strong></p> *}
    {/if}
{*        <label>{'Select siteaccess'|i18n( 'design/standard/design/toolbar' )}</label><div class="labelbreak"></div> *}

        <select name="CurrentSiteAccess">
            {section var=siteaccess loop=$siteaccess_list}
                {if eq( $current_siteaccess, $siteaccess )}
                    <option value="{$siteaccess}" selected="selected">{$siteaccess}</option>
                {else}
                <option value="{$siteaccess}">{$siteaccess}</option>
            {/if}
        {/section}
        </select>

</div>

{* DESIGN: Content END *}</div></div></div>

<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
        <input class="button" type="submit" value="{"Set"|i18n("design/standard/design/toolbar")}" name="SelectCurrentSiteAccessButton" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>

</div>


<div class="context-block">

{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">

<h2 class="context-title">{'Available toolbars'|i18n( 'design/standard/design/toolbar' )}</h2>

{* DESIGN: Subline *}<div class="header-subline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-bl"><div class="box-br"><div class="box-content">

<table class="list" cellspacing="0">
{section var=toolbar loop=$toolbar_list sequence=array( bglight, bgdark )}
    <tr>
        <td class="{$toolbar.sequence}">
        <a href={concat( "design/toolbar/", $current_siteaccess, "/", $toolbar )|ezurl}>{$toolbar}</a>
        </td>
    </tr>
{/section}
</table>

{* DESIGN: Content END *}</div></div></div></div></div></div>

</div>

</form>