{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<label>{$attribute.content.name|wash( xhtml )}:</label>
<select name="eZOption[{$attribute.id}]">
{section var=Options loop=$attribute.content.option_list}
<option value="{$Options.item.id}">{$Options.item.value} - {$Options.item.additional_price|l10n( currency )}</option>
{/section}
</select>