-- WARNING ****** WARNING
--
-- This file will remove data from the following tables
--  - ezsession
--  - ezpreferences
--  - ezhistory
--  - ezcontentbrowserecent
--  - ezcontentbrowsebookmark
--  - eztipafriend_counter
--  - ezbasket
--  - ezcollab_item
--  - ezcollab_item_group_link
--  - ezcollab_item_message_link
--  - ezcollab_item_participant_link
--  - ezcollab_item_status
--  - ezcollab_notification_rule
--  - ezcollab_profile
--  - ezcollab_simple_message
--  - ezforgot_password
--  - ezgeneral_digest_user_settings
--  - ezinfocollection
--  - ezinfocollection_attribute
--  - ezoperation_memento
--  - eznotificationevent
--  - ezorder
--  - ezorder_item
--  - ezproductcollection
--  - ezproductcollection_item
--  - ezproductcollection_item_opt
--  - ezsubtree_notification_rule
--  - ezwishlist
--  - ezworkflow_process


DELETE FROM ezsession;
DELETE FROM ezpreferences;
DELETE FROM ezhistory;
DELETE FROM ezcontentbrowserecent;
DELETE FROM ezcontentbrowsebookmark;
DELETE FROM eztipafriend_counter;
DELETE FROM ezbasket;
DELETE FROM ezcollab_item;
DELETE FROM ezcollab_item_group_link;
DELETE FROM ezcollab_item_message_link;
DELETE FROM ezcollab_item_participant_link;
DELETE FROM ezcollab_item_status;
DELETE FROM ezcollab_notification_rule;
DELETE FROM ezcollab_profile;
DELETE FROM ezcollab_simple_message;
DELETE FROM ezforgot_password;
DELETE FROM ezgeneral_digest_user_settings;
DELETE FROM ezinfocollection;
DELETE FROM ezinfocollection_attribute;
DELETE FROM ezoperation_memento;
DELETE FROM eznotificationevent;
DELETE FROM ezorder;
DELETE FROM ezorder_item;
DELETE FROM ezproductcollection;
DELETE FROM ezproductcollection_item;
DELETE FROM ezproductcollection_item_opt;
DELETE FROM ezsubtree_notification_rule;
DELETE FROM ezwishlist;
DELETE FROM ezworkflow_process;
