{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <p>{'Diff output disabled for %type'|i18n( 'design/standard/content/datatype',, hash( '%type', $attribute.data_type_string ) )}</p>
</div>
