<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1061114927;

$Parameters = array( "name" => "news_site",
                     "summary" => "News site",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => false,
                     "extension" => false,
                     "ezpublish" => array( "version" => "3.2.0-1",
                                           "named-version" => "3.2 pre-alpha" ),
                     "maintainers" => array( array( "name" => "Anonymous User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead",
                                                    "modified" => "1061231760" ) ),
                     "packaging" => array( "timestamp" => "1061231760",
                                           "host" => "bf.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1061231760" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1061231760",
                                                  "person" => "Anonymous User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package" ),
                                                  "release" => "1",
                                                  "modified" => "1061231760" ) ),
                     "file-list" => array( "default" => array( array( "name" => false,
                                                                      "subdirectory" => false,
                                                                      "type" => "design",
                                                                      "role" => false,
                                                                      "path" => false,
                                                                      "file-type" => false,
                                                                      "design" => "news",
                                                                      "copy-file" => false,
                                                                      "modified" => "1061231761",
                                                                      "md5" => false ),
                                                               array( "name" => "override.ini.append",
                                                                      "subdirectory" => "settings/siteaccess/news",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "path" => "settings/siteaccess/news/override.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061231761",
                                                                      "md5" => "e1dd5ea39c5dc492041d22664c02e7a8" ),
                                                               array( "name" => "site.ini.append",
                                                                      "subdirectory" => "settings/siteaccess/news",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "path" => "settings/siteaccess/news/site.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061231762",
                                                                      "md5" => "b9f9d5bfcaf674b24582afacbec0162b" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "path" => "newsthumbnail.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061231765",
                                                                      "md5" => "15902c814e2d28ecd29853b36a6a1686" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1061231761" ) ),
                                              "requires" => array( array( "type" => "ezdb",
                                                                          "name" => "mysql",
                                                                          "value" => false,
                                                                          "modified" => "1061231763" ),
                                                                   array( "type" => "ezdb",
                                                                          "name" => "postgresql",
                                                                          "value" => false,
                                                                          "modified" => "1061231763" ),
                                                                   array( "type" => "ezdb",
                                                                          "name" => "postgresql",
                                                                          "value" => false,
                                                                          "modified" => "1061231764" ) ),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1061231761",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ),
                                         array( "path" => "packages/news.sql",
                                                "database-type" => "mysql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061231763",
                                                "os" => false,
                                                "filename" => "news.sql",
                                                "sub-directory" => false ),
                                         array( "path" => "kernel/sql/postgresql/kernel_schema.sql",
                                                "database-type" => "postgresql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061231763",
                                                "os" => false,
                                                "filename" => "kernel_schema.sql",
                                                "sub-directory" => false ),
                                         array( "path" => "kernel/sql/postgresql/cleandata.sql",
                                                "database-type" => "postgresql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061231764",
                                                "os" => false,
                                                "filename" => "cleandata.sql",
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1061231761",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1061231760",
                             "version-number" => "1061231760",
                             "release-number" => "1061231760",
                             "licence" => "1061231760",
                             "state" => "1061231760",
                             "summary" => 1061231765 );
$RepositoryPath = "packages";
?>
