{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="image-thumbnail-item">

    <label for="related-object-id-{$related_object.id}">{attribute_view_gui attribute=$related_object.data_map.image image_class=small}</label>

    <p class="checkbox"><input type="checkbox" id="related-object-id-{$related_object.id}" name="DeleteRelationIDArray[]" value="{$related_object.id}" /><label for="related-object-id-{$related_object.id}">{$related_object.name|wash}</label></p>

    <input class="linkbox" type="text" value="&lt;object id={$related_object.id} /&gt;">

</div>
