{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="maincontentheader">
<h1>
    {"Choose owner of imported objects"|i18n("design/standard/rss")}
</h1>
</div>

<p>
    {"Please select the owner of the objects to import

    Select the user then click the %buttonname button.
    Using the recent and bookmark items for quick selection is also possible.
    Click on placement names to change the browse listing."
    |i18n("design/standard/rss",,
          hash('%buttonname','Select'|i18n("design/standard/rss")))
    |nl2br}
</p>