{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default $countries = ezini('CountrySettings','Countries', 'content.ini' )
         $max_len = 20
         $select_size = 1}
<select name="{$select_name}" size="{$select_size}">
{if and( is_set( $default_val ), is_set( $default_desc ) )}
    <option {if eq( $current_val, false )}selected="selected"{/if} value="{$default_val}">{$default_desc}</option>
{/if}
{foreach $countries as $country}
    <option {if eq( $country, $current_val )}selected="selected"{/if} value="{$country}">{$country|shorten($max_len)}</option>
{/foreach}
</select>
{/default}

