{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute container="fieldset"}
<{$container}>
{* parent_node is default_selection_node or root *}
{let class_content=$attribute.contentclass_attribute.content
	 parent_node=cond(and(is_set($class_content.default_selection_node),$class_content.default_selection_node|eq(0)|not),$class_content.default_selection_node,1)
	 nodesList=cond(and(is_set($class_content.filter_class),$class_content.filter_class|eq(0)|not),
                   fetch( content, tree,
                             hash( parent_node_id, $parent_node,
                                   class_filter_type,'include',
                                   class_filter_array, array($class_content.filter_class),
                                   sort_by, array('name',true()),
                                   main_node_only, true() ) ),
                   fetch( content, list,
                             hash( parent_node_id, $parent_node,
                                   sort_by, array('name',true())
                                    ) )
                  )
}

{switch match=$class_content.selection_type}

{case match=0} {* Browse *}
    <p>{'Please select another selection method.'|i18n( 'design/standard/content/datatype' )}</p>
    {*{section show=$attribute.content}
        <p class="box">{content_view_gui view=text_linked content_object=$attribute.content}</p>
    {section-else}
        <p class="box">{"No relation"|i18n("design/standard/content/datatype")}</p>
    {/section}

    <input type="hidden" name="{$attribute_base}_data_object_relation_id_{$attribute.id}" value="{$attribute.data_int}" />
    {section show=$attribute.content}
        <input class="button" type="submit" name="BrowseObjectButton_{$attribute.id}" value="{'Replace object'|i18n('design/standard/content/datatype')}" />
        <input class="button" type="submit" name="RemoveObjectButton_{$attribute.id}" value="{'Remove object'|i18n('design/standard/content/datatype')}" />
    {section-else}
        <input class="button" type="submit" name="BrowseObjectButton_{$attribute.id}" value="{'Find object'|i18n('design/standard/content/datatype')}" />
    {/section}
    <input type="hidden" name="CustomActionButton[{$attribute.id}_set_object_relation]" value="{$attribute.id}" />
    *}
{/case}

{case match=1} {* Dropdown list *}
    <div class="buttonblock">
    <input type="hidden" name="single_select_{$attribute.id}" value="1" />
    <select name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[{section show=is_set($node)}{$node.node_id}{section-else}empty{/section}]">
        {section show=$attribute.contentclass_attribute.is_required|not}
            <option value="" {section show=eq( $attribute.data_int, '' )}selected="selected"{/section}>{'No relation'|i18n( 'design/standard/content/datatype' )}</option>
        {/section}
        {section var=node loop=$nodesList}
            <option value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '', 'selected="selected"' )}>{$node.name|wash}</option>
        {/section}
    </select>
    </div>
{/case}

{case match=2} {* radio buttons list *}
    <input type="hidden" name="single_select_{$attribute.id}" value="1" />
    {section show=$attribute.contentclass_attribute.is_required|not}
        <input type="radio" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[single]"
    {section show=eq( $attribute.data_int, '' )}selected="selected"{/section}>{'No relation'|i18n( 'design/standard/content/datatype' )}</input><br />{/section}
    {section var=node loop=$nodesList}
	<input type="radio" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[single]" value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '', 'checked="checked"' )}>{$node.name|wash}</input>  <br/>
    {/section}
{/case}

{case match=3} {* check boxes list *}
    {section var=node loop=$nodesList}
       <input type="checkbox" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[{$node.node_id}]" value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '', 'checked="checked"' )} />{$node.name|wash} <br/>
    {/section}
{/case}

{case match=4} {* Multiple List *}
    <div class="buttonblock">
    <select name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[]" size="10" multiple>
        {section var=node loop=$nodesList}
            <option value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '', 'selected="selected"' )}>
	    {$node.name|wash}</option>
        {/section}
    </select>
    </div>
{/case}


{case match=5} {* Template based, multi *}
    <div class="buttonblock">
    <div class="templatebasedeor">
        <ul>
        {section var=node loop=$nodesList}
           <li>
                <input type="checkbox" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[{$node.node_id}]" value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '', 'checked="checked"' )}>
                        {node_view_gui content_node=$node view=enhancedobjectrelation}
                </input>
           </li>
        {/section}
        </ul>
    </div>
    </div>
{/case}

{case match=6} {* Template based, single *}
    <div class="buttonblock">
    <div class="templatebasedeor">
        <ul>
        <li>
            {section show=$attribute.contentclass_attribute.is_required|not}
            <input type="radio" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[single]" {section show=eq( $attribute.data_int, '')} selected="selected"{/section}>{'No relation'|i18n( 'design/standard/content/datatype' )}</input><br />
            {/section}
        </li>
        {section var=node loop=$nodesList}
           <li>
                <input type="radio" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[single]" value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '', 'checked="checked"' )}>
                        {node_view_gui content_node=$node view=enhancedobjectrelation}
                </input>
           </li>
        {/section}
        </ul>
   </div>
   </div>
{/case}

{/switch}
{section show = and( ne( 0, $class_content.default_placement_node ), ne( 0, $class_content.filter_class ), ne( $class_content.selection_type, 0 ) )}
    {def $defaultNode = fetch( content, node, hash( node_id, $class_content.default_placement_node ))}
    {if and( is_set( $defaultNode ), $defaultNode.can_create )}
        <input name="attribute_{$attribute.id}_new_object_name" id="attribute_{$attribute.id}_new_object_name" style="display:none;" />
        <input class="button" type="button" value="Create New" name="CustomActionButton[{$attribute.id}_new_object]" onclick="var editfield=document.getElementById('attribute_{$attribute.id}_new_object_name');editfield.style.display='block';editfield.focus();this.style.display='none';return false;" />
    {/if}
{/section}

{/let}
</{$container}>
{/default}
