{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
<input class="box" type="text" name="{$attribute_base}_data_integer_{$attribute.id}" size="10" value="{$attribute.data_int}" />
{/default}