{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}

{section var=GroupList loop=$attribute.content.optiongroup_list}
<div class="block">
    <fieldset class="multioption">

        {include uri='design:content/datatype/edit/multioption2/multioption2_rules.tpl' name=ChildGroup1 attribute=$attribute group=$GroupList.item parent_group_id=$attribute.content.group_id depth=1 rules=$attribute.content.rules}
    </fieldset>
</div>
{/section}
<div class="block">
<input class="button" type="submit" name="CustomActionButton[{$attribute.id}_switch-mode_options]" value="{'Options'|i18n('design/standard/content/datatype')}" title="{'Set rules'|i18n('design/standard/content/datatype')}" />
<input class="button" type="submit" name="CustomActionButton[{$attribute.id}_reset-rules]" value="{'Reset rules'|i18n('design/standard/content/datatype')}" title="{'Set rules'|i18n('design/standard/content/datatype')}" />
<input type="hidden" name = "{$attribute_base}_data_edit_mode_{$attribute.id}" value="rules" />
</div>
{/default}
