{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
  This file is included in the ezobjectrelationlist.tpl templates in browse mode.
  in admin design it provides a way to add a related object directly from an file upload
*}
