{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form action={'class/grouplist'|ezurl} method="post" name="GroupList">

<div class="context-block">
<h2 class="context-title">{'Class groups'|i18n( 'design/admin/class/list' )}&nbsp;[{$groups|count}]</h2>

<table class="list" cellspacing="0">
<tr>
    <th class="tight">&nbsp;</th>
    <th>{'Name'|i18n( 'design/admin/class/list' )}</th>
    <th>{'Modifier'|i18n( 'design/admin/class/list' )}</th>
    <th>{'Modified'|i18n( 'design/admin/class/list' )}</th>
    <th>{'Edit'|i18n( 'design/admin/class/list' )}</th>
</tr>

{section var=Groups loop=$groups sequence=array( bglight, bgdark )}
<tr class="{$Groups.sequence}">
    <td><input type="checkbox" name="DeleteIDArray[]" value="{$Groups.item.id}"></td>

    <td>{$Groups.item.name|classgroup_icon( small, $Groups.item.name )}&nbsp;<a href={concat( $module.functions.classlist.uri, '/', $Groups.item.id)|ezurl}>{$Groups.item.name|wash}</a></td>
    <td>{content_view_gui view=text_linked content_object=$Groups.item.modifier.contentobject}</td>
    <td>{$Groups.item.modified|l10n(shortdatetime)}</td>
    <td><a href={concat($module.functions.groupedit.uri,"/",$Groups.item.id)|ezurl}><img class="button" src={"edit.png"|ezimage} width="16" height="16" alt="Edit" /></a></td>
</tr>
{/section}
</table>

<div class="controlbar">
<div class="block">
    <input class="button" type="submit" name="RemoveGroupButton" value="{'Remove selected'|i18n( 'design/admin/class/list' )}" />
    <input class="button" type="submit" name="NewGroupButton" value="{'New group'|i18n( 'design/admin/class/list' )}" />
</div>
</div>

</div>


<div class="context-block">
<h2 class="context-title">{'Recently modified classes'|i18n( 'design/admin/class/list' )}</h2>

{let latest_classes=fetch( class, latest_list, hash( limit, 10 ) )}

{section show=$latest_classes}

    <table class="list" cellspacing="0">
    <tr>
        <th>{'Name'|i18n( 'design/admin/class/list')}</th>
        <th>{'ID'|i18n( 'design/admin/class/list' )}</th>
        <th>{'Identifier'|i18n( 'design/admin/class/list' )}</th>
        <th>{'Modifier'|i18n( 'design/admin/class/list' )}</th>
        <th>{'Modified'|i18n( 'design/admin/class/list' )}</th>
        <th>{'Edit'|i18n( 'design/admin/class/list' )}</th>
    </tr>

    {section var=class loop=$latest_classes sequence=array( bglight, bgdark )}
        <tr class="{$class.sequence}">
            <td>{$class.identifier|class_icon( small, $class.name )}&nbsp;<a href={concat( '/class/view/', $class.item.id )|ezurl}>{$class.item.name|wash}</a></td>
            <td>{$class.item.id}</td>
            <td>{$class.item.identifier|wash}</td>
            <td>{content_view_gui view=text_linked content_object=$class.item.modifier.contentobject}</td>
            <td>{$class.item.modified|l10n(shortdatetime)}</td>
            <td><a href={concat( 'class/edit/', $class.item.id )|ezurl}><img class="button" src={'edit.png'|ezimage} width="16" height="16" alt="edit" /></a></td>
        </tr>
    {/section}
    </table>
{/section}

</div>



</form>
{/let}
