{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $dynamic_csm_disabled = ezini('TreeMenu','Dynamic','contentstructuremenu.ini')|ne('enabled')}

{if $dynamic_csm_disabled}
<style type="text/css">

div#contentstructure ul#content_tree_menu ul li {ldelim} padding-left: 0; {rdelim}
div#contentstructure ul#content_tree_menu ul ul {ldelim} margin-left: 20px; {rdelim}

</style>
{/if}

{literal}
<!--[if lt IE 8]>
<style>
.float-break /* Terminate floating elements flow in IE < 8 */
{
    height: 1%;
}
</style>
<![endif]-->
{/literal}