{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{literal}
<!--[if lt IE 8]>
<style>
.float-break /* Terminate floating elements flow in IE < 8 */
{
    height: 1%;
}
</style>
<![endif]-->
{/literal}