{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{'First name'|i18n('design/standard/shop')}: {$order.account_information.first_name}<br />
{'Last name'|i18n('design/standard/shop')}: {$order.account_information.last_name}<br />
{'Email'|i18n('design/standard/shop')}: {$order.account_information.email}<br />
{'Address'|i18n('design/standard/shop')}: {$order.account_information.address}<br />
<br />