{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"User account information"|i18n("design/standard/content/datatype")}

{"User ID"|i18n("design/standard/content/datatype")}
{$attribute.content.contentobject_id}

{"Username"|i18n("design/standard/content/datatype")} {$attribute.content.login|wash(xhtml)}
{"Email"|i18n("design/standard/content/datatype")} {$attribute.content.email|wash(email)}
