{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default object_name=$object.name}
{section show=$object.main_node_id|null|not}
    <a href={$object.main_node.url_alias|ezurl}>{$object_name|wash}</a>
{section-else}
    {$object_name|wash}
{/section}
{/default}
