<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1061114927;

$Parameters = array( "name" => "news_site",
                     "summary" => "News site",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => false,
                     "extension" => false,
                     "ezpublish" => array( "version" => "3.2.0-1",
                                           "named-version" => "3.2 beta1" ),
                     "maintainers" => array( array( "name" => "Anonymous User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead",
                                                    "modified" => "1061309397" ) ),
                     "packaging" => array( "timestamp" => "1061309397",
                                           "host" => "bf.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1061309397" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1061309397",
                                                  "person" => "Anonymous User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package" ),
                                                  "release" => "1",
                                                  "modified" => "1061309397" ) ),
                     "file-list" => array( "default" => array( array( "name" => false,
                                                                      "subdirectory" => false,
                                                                      "type" => "design",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => false,
                                                                      "path" => false,
                                                                      "file-type" => false,
                                                                      "design" => "news",
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309398",
                                                                      "md5" => false ),
                                                               array( "name" => "override.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "news",
                                                                      "variable-name" => "user_siteaccess",
                                                                      "path" => "settings/siteaccess/news/override.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309400",
                                                                      "md5" => "e1dd5ea39c5dc492041d22664c02e7a8" ),
                                                               array( "name" => "site.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "news",
                                                                      "variable-name" => "user_siteaccess",
                                                                      "path" => "settings/siteaccess/news/site.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309401",
                                                                      "md5" => "cbd00572973fc961f800bf188d82e96b" ),
                                                               array( "name" => "override.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "admin",
                                                                      "variable-name" => "admin_siteaccess",
                                                                      "path" => "settings/siteaccess/admin/override.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309403",
                                                                      "md5" => "50f4805254652ccea3c0191a23ce5c21" ),
                                                               array( "name" => "site.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "admin",
                                                                      "variable-name" => "admin_siteaccess",
                                                                      "path" => "settings/siteaccess/admin/site.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309403",
                                                                      "md5" => "47a0ba3f8010fba23cc881208bf4bfc1" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => false,
                                                                      "path" => "newsthumbnail.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309406",
                                                                      "md5" => "ac4fc22bd08c13f9ee5e02ae575ff941" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1061309398" ) ),
                                              "requires" => array( array( "type" => "ezdb",
                                                                          "name" => "mysql",
                                                                          "value" => false,
                                                                          "modified" => "1061309404" ),
                                                                   array( "type" => "ezdb",
                                                                          "name" => "postgresql",
                                                                          "value" => false,
                                                                          "modified" => "1061309405" ) ),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1061309398",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ),
                                         array( "path" => "packages/news.sql",
                                                "database-type" => "mysql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061309404",
                                                "os" => false,
                                                "filename" => "news.sql",
                                                "sub-directory" => false ),
                                         array( "path" => "packages/news_postgresql.sql",
                                                "database-type" => "postgresql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061309405",
                                                "os" => false,
                                                "filename" => "news_postgresql.sql",
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1061309398",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1061309397",
                             "version-number" => "1061309397",
                             "release-number" => "1061309397",
                             "licence" => "1061309397",
                             "state" => "1061309397",
                             "summary" => 1061309407 );
$RepositoryPath = "packages";
?>
