<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "corporate_blue",
                     "development" => false,
                     "summary" => "Blue CSS design for corporate",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => "sitestyle",
                     "extension" => false,
                     "is_installed" => false,
                     "is_active" => true,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "3.3.0-1",
                                           "named-version" => "3.3 beta 1" ),
                     "maintainers" => array(),
                     "packaging" => array( "timestamp" => "1069864035",
                                           "host" => "jb.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1069864035" ) ),
                     "groups" => array(),
                     "changelog" => array(),
                     "file-list" => array( "default" => array( array( "name" => "corporate-blue.css",
                                                                      "subdirectory" => "design/corporate/stylesheets",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "cssfile",
                                                                      "path" => "design/corporate/stylesheets/corporate-blue.css",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864035",
                                                                      "md5" => "f9c3caca31e386ebe0ab27b1394ccdff" ),
                                                               array( "name" => "header_image.gif",
                                                                      "subdirectory" => "design/corporate/images",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/corporate/images/header_image.gif",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864036",
                                                                      "md5" => "70937ac530143162903dda503637af54" ),
                                                               array( "name" => "infobox_image.gif",
                                                                      "subdirectory" => "design/corporate/images",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/corporate/images/infobox_image.gif",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864036",
                                                                      "md5" => "a9857d5ce12c57e6b1d888806c58cb49" ),
                                                               array( "name" => "header_image-repeat.gif",
                                                                      "subdirectory" => "design/corporate/images",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/corporate/images/header_image-repeat.gif",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864037",
                                                                      "md5" => "8396d5f3a3ae6b6ed420e968eea955dc" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "design/corporate/images/corporate-blue.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => true,
                                                                      "modified" => 1069864037,
                                                                      "md5" => "f7c59dd8399055542ce224fb87680be0" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1069864035" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1069864035",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1069864035",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1069864035",
                             "summary" => "1069864035",
                             "type" => "1069864035",
                             "version-number" => "1069864035",
                             "release-number" => "1069864035",
                             "licence" => "1069864035",
                             "state" => "1069864035" );
$InstallData = array();
$RepositoryPath = "var/corporate/storage/packages";
?>
