{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let class_list=fetch( class, list )}
<div id="package" class="create">
    <div id="sid-{$current_step.id|wash}" class="pc-{$creator.id|wash}">

    <form enctype="multipart/form-data" method="post" action={'package/create'|ezurl}>

    {include uri="design:package/create/error.tpl"}

    {include uri="design:package/header.tpl"}

    <p>{'Select an image file to be included in the package then click Next.
Click "Next" without choosing an image to continue to the next step.'|i18n('design/admin/package')|break}</p>

    {section show=$persistent_data.imagefiles}
    <div class="files">
        <h3>{'Currently added image files'|i18n('design/admin/package')}</h3>
        <ul>
            {section var=imagefile loop=$persistent_data.imagefiles}
            <li>{$imagefile.filename|wash}</li>
            {/section}
        </ul>
    </div>
    {/section}

    <div class="block">
    <input type="hidden" name="MAX_FILE_SIZE" value="32000000" />
    <input class="box" name="PackageImageFile" type="file" />
    </div>

    {include uri="design:package/navigator.tpl"}

    </form>

    </div>
</div>
{/let}
