{* DO NOT EDIT THIS FILE! Use an override template instead. *}
     {section show=$validation.processed}
        {section show=or($validation.attributes,$validation.placement)}

          <div class="message-warning">
          {section show=and($validation.attributes,$validation.placement)}
            <h2><span class="time">[{currentdate()|l10n( shortdatetime )}]</span> {"Validation failed"|i18n("design/standard/content/edit")}</h2>
          {section-else}
            {section show=$validation.attributes}
            <h2><span class="time">[{currentdate()|l10n( shortdatetime )}]</span> {"Input did not validate"|i18n("design/standard/content/edit")}</h2>
            {section-else}
            <h2><span class="time">[{currentdate()|l10n( shortdatetime )}]</span> {"Location did not validate"|i18n("design/standard/content/edit")}</h2>
            {/section}
          {/section}
          <ul>
          {section name=UnvalidatedPlacements loop=$validation.placement show=$validation.placement}
            <li>{$:item.text}</li>
          {/section}
          {section name=UnvalidatedAttributes loop=$validation.attributes show=$validation.attributes}
            <li>{$:item.name|wash}: {$:item.description}</li>
          {/section}
          </ul>
          </div>

        {section-else}
	  {section show=$validation_log}
	  <div class="message-warning">
          <h2><span class="time">[{currentdate()|l10n( shortdatetime )}]</span> {"Input was partially stored"|i18n("design/standard/content/edit")}</h2>
	      {section name=ValidationLog loop=$validation_log}
                  <h3>{$:item.name|wash}:</h3>
	          <ul>
	          {section name=LogMessage loop=$:item.description}
	              <li>{$:item}</li>
	          {/section}
                  </ul>
              {/section}
          </div>
	  {section-else}
          <div class="message-feedback">
          <h2><span class="time">[{currentdate()|l10n( shortdatetime )}]</span> {"Input was stored successfully"|i18n("design/standard/content/edit")}</h2>
          </div>
	  {/section}
        {/section}
    {/section}
