{* DO NOT EDIT THIS FILE! Use an override template instead. *}
    {section var=attribute loop=$content_attributes sequence=array(bglight,bgdark)}
    <div class="block">

    {* only show edit GUI if we can edit *}
    {section show=and(eq($attribute.item.can_translate,0),
                      ne($object.default_language,$attribute.item.language_code) ) }
        <label>{$attribute.item.contentclass_attribute_name|wash}:</label>
        <input type="hidden" name="ContentObjectAttribute_id[]" value="{$attribute.item.id}" />
        {attribute_view_gui attribute_base=$attribute_base attribute=$attribute.item}
        </div>
    {section-else}
        <label{section show=$attribute.item.has_validation_error} class="message-error"{/section}>{$attribute.item.contentclass_attribute_name|wash}{section show=$attribute.item.is_required}<span class="required">({"required"|i18n( 'admin/content/edit' )})</span>{/section}{section show=$attribute.item.is_information_collector}<span class="collector">({"information collector"|i18n( 'admin/content/edit' )})</span>{/section}:</label>
        <input type="hidden" name="ContentObjectAttribute_id[]" value="{$attribute.item.id}" />
        {attribute_edit_gui attribute_base=$attribute_base attribute=$attribute.item} 
    </div>

    {/section}

    {/section}
