{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let root_node=fetch( content, node, hash( node_id, $browse.content.node_id ) )}
<div class="maincontentheader">
<h1>
    {'Choose new location for the copy of subtree of node %node_name'
     |i18n( 'design/standard/content/view',, hash( '%node_name', $root_node.name|wash ) )}
</h1>
</div>

<p>
    {"Please choose where you want to copy subtree of node %node_name.

    Select the new location then click the %buttonname button.
    Using the recent and bookmark items for quick placement is also possible.
    Click on placement names to change the browse listing."
    |i18n( 'design/standard/content/view',,
           hash( '%node_name', $root_node.name|wash,
                 '%buttonname','Select'|i18n('design/standard/content/view' ) ) )
    |nl2br}
</p>
{/let}
