{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{"Collected info"|i18n("design/standard/content/view")}</h1>

<h2>{$collection.object.name|wash}</h2>


{section loop=$collection.attributes}

<h3>{$:item.contentclass_attribute_name|wash}</h3>

{attribute_result_gui attribute=$:item}

{/section}
