{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"Customer information"|i18n('design/standard/shop')}:
{$order.account_information.first_name} {$order.account_information.last_name}{if $order.account_information.street1} ({$order.account_information.street1}){/if}

{"Email"|i18n('design/standard/shop')}:
{$order.account_information.email}

{"Shipping address"|i18n('design/standard/shop')}:
{$order.account_information.street2}
{$order.account_information.zip} {$order.account_information.place}

{if $order.account_information.state}{$order.account_information.state} {/if}{$order.account_information.country}
