{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{'First name'|i18n('design/standard/shop')}: {$order.account_information.first_name}
{'Last name'|i18n('design/standard/shop')}: {$order.account_information.last_name}
{'Email'|i18n('design/standard/shop')}: {$order.account_information.email}
{'Address'|i18n('design/standard/shop')}: {$order.account_information.address}