{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=latin1?*}

<form method="post" action="{$script}">

    <div align="center">
        <h1>{"Creating sites"|i18n("design/standard/setup/init")}</h1>
    </div>

    <p>
        {'The setup wizard was not able to complete the creation of your selected sites.'|i18n( 'design/standard/setup/init' )}
    </p>


    <p>
        {'The following errors were detected'|i18n( 'design/standard/setup/init' )}:
    </p>

    <ul class="error">
        {section var=error loop=$error_list}
            <li>
                <label>{$error.code|wash}</label>{$error.text|wash|break}
            </li>
        {/section}
    </ul>

    <p>
        {'If you think you have fixed the errors you can try then click the "Retry" button.'|i18n( 'design/standard/setup/init' )}
    </p>

    <div class="buttonblock" align="right">
        {include uri='design:setup/init/navigation.tpl' retry=true() dont_show_back=true() dont_show_forward=true()}
    </div>
    {include uri='design:setup/persistence.tpl'}
</form>
