{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"eZ Publish supports multiple languages."|i18n("design/standard/setup/init")}
<p></p>
{"The selected languages are used to determine character sets, date / number formats, etc."|i18n("design/standard/setup/init")}
<p></p>
{"These and other additional languages can also be installed later."|i18n("design/standard/setup/init")}
<p></p>
{"For more information about language customization, please refer to the %1."|i18n("design/standard/setup/init",,array(concat( '<a href="http://ez.no/ez_publish/documentation/configuration/configuration/language_and_charset" target="_blank">', "documentation"|i18n("design/standard/setup/init", 'language information link'), '</a>' ) ) )}
