{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"The eZ Publish system can use proxy server to connect to Internet."|i18n("design/standard/setup/init")}
<p></p>
{"That is the help chapter about proxy."|i18n("design/standard/setup/init")}
<p></p>