{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=latin1?*}
{include uri='design:setup/setup_header.tpl' setup=$setup}

<form method="post" action="{$script}">

{let has_variations=false()}

{section loop=$available_languages}
{section-exclude match=$:item.country_variation}
{set has_variations=true()}
{/section}

{if eq($regional_info.language_type,1)}
 <p>
  {"Select the language this site should support."|i18n("design/standard/setup/init")}
  {if $has_variations}
   {"Select your language then click the"|i18n("design/standard/setup/init")} <i>{"Summary"|i18n("design/standard/setup/init")}</i> {"button, or the"|i18n("design/standard/setup/init")} <i>{"Language Details"|i18n("design/standard/setup/init")}</i> {"button to select language variations."|i18n("design/standard/setup/init")}
  {else}
   {"Select your language then click the"|i18n("design/standard/setup/init")} <i>{"Summary"|i18n("design/standard/setup/init")}</i> {"button."|i18n("design/standard/setup/init")}
  {/if}
 </p>
{else}
 <p>
  {"Select the languages this site should support. Select your primary language and check any additional languages."|i18n("design/standard/setup/init")}
  {if $has_variations}
   {"Once you are done, click the"|i18n("design/standard/setup/init")} <i>{"Summary"|i18n("design/standard/setup/init")}</i> {"button, or the"|i18n("design/standard/setup/init")} <i>{"Language Details"|i18n("design/standard/setup/init")}</i> {"button to select language variations."|i18n("design/standard/setup/init")}
  {else}
   {"Once you are done, click the"|i18n("design/standard/setup/init")} <i>{"Summary"|i18n("design/standard/setup/init")}</i> {"button."|i18n("design/standard/setup/init")}
  {/if}
 </p>
 {if eq($regional_info.language_type,3)}
  <p>{"The languages you choose will help determine the charset to use on the site."|i18n("design/standard/setup/init")}</p>
 {/if}
{/if}

<div class="input_highlight">
<table cellspacing="0" cellpadding="0" border="0">
<tr><th>{"Language name"|i18n("design/standard/setup/init")}</th><th colspan="2">{"Selection"|i18n("design/standard/setup/init")}</th></tr>
{section name=Language loop=$available_languages}
{section-exclude match=$:item.country_variation}
<tr>
  <td class="normal">
    {$:item.language_name}
  </td>
{if eq($regional_info.language_type,1)}
  <td align="right" class="normal">
{else}
  <td align="right" colspan="2" class="normal">
{/if}
    <input type="radio" name="eZSetupPrimaryLanguage" value="{$:item.locale_full_code}" {if eq($regional_info.primary_language,$:item.locale_full_code)}checked="checked"{/if} />
  </td>
{if ne($regional_info.language_type,1)}
  <td align="right" class="normal">
    <input type="checkbox" name="eZSetupLanguages[]" value="{$:item.locale_full_code}" {switch match=$:item.locale_full_code}{case in=$regional_info.languages}checked="checked"{/case}{case/}{/switch} />
  </td>
{/if}
</tr>
{/section}
</table>
</div>

  <div class="buttonblock">
    <input type="hidden" name="ChangeStepAction" value="" />
{* {if ne($regional_info.language_type,1)} *}
    <input class="defaultbutton" type="submit" name="StepButton_7" value="{'Summary'|i18n('design/standard/setup/init')} >>" />
{if $has_variations}
    <input type="hidden" name="eZSetupChooseVariations" value="" />
    <input class="button" type="submit" name="StepButton_6" value="{'Language Details'|i18n('design/standard/setup/init')} >" />
{/if}
{* {/if} *}
  </div>
  {include uri='design:setup/persistence.tpl'}
</form>
{/let}
