{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"By sending registration the following data will be sent to eZ Systems"|i18n("design/standard/setup/init")}
<ul>
  <li>{"System details (OS type, etc)"|i18n("design/standard/setup/init")}</li>
  <li>{"The test results"|i18n("design/standard/setup/init")}</li>
  <li>{"The database type"|i18n("design/standard/setup/init")}</li>
  <li>{"The site name"|i18n("design/standard/setup/init")}</li>
  <li>{"The url of the site"|i18n("design/standard/setup/init")}</li>
  <li>{"Languages chosen"|i18n("design/standard/setup/init")}</li>
</ul>
<p></p>
{"This data will help to improve future releases of eZ Publish."|i18n("design/standard/setup/init")}