{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"Select which sites you would like to install on your system."|i18n("design/standard/setup/init")}
<p></p>
{"Each package will create a unique web site."|i18n("design/standard/setup/init")}
<p></p>
{"Since each web site is unique, each package requires a unique database."|i18n("design/standard/setup/init")}