{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"You may modify the details for each site."|i18n("design/standard/setup/init")}
<p></p>
{"For more information about how to configure site access, refer to the %1"|i18n("design/standard/setup/init",,array(concat( '<a href="http://doc.ez.no/eZ-Publish/Technical-manual/5.x/Concepts-and-basics/Configuration/Site-management" target="_blank">', "documentation"|i18n("design/standard/setup/init",'site access documentation link'), '</a>' ) ) )}
<p></p>
{"Use the refresh button to update the database listing."|i18n("design/standard/setup/init")}