{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"Each site comes with a predefined set of functionality, however it is possible to add extra functionality.
This functionality is also available at a later time from the Administration Interface."|i18n("design/standard/setup/init")}
