{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=latin1?*}

<form enctype="multipart/form-data" method="post" action="{$script}">

  <div align="center">
    <h1>{"Site package"|i18n("design/standard/setup/init")}</h1>
  </div>

  <p>
    {"Please choose one site type you would like to test or base your sites on. Use Plain if you wish to start from scratch."i18n("design/standard/setup/init")}
  </p>

{section show=$error}
<div class="error">

{*
<p>
{$error|wash}
</p>
*}

<p>
  <h2>{"Error"|i18n("design/standard/setup/init")}</h2>
  <ul>
    <li>{$error|wash}</li>
  </ul>
</p>

</div>
{/section}

<table border="1" cellspacing="1" cellpadding="0">
<tr><td colspan="4"><h2>{'Site packages'|i18n('design/standard/setup/init')}:</h2></td></tr>
{if is_set( $site_packages )}
    {foreach $site_packages as $package_info}
    <tr>
    <td>
        {if is_set( $package_info.url )}
      <input id="{$package_info.name|wash}" type="radio" name="eZSetup_site_type" value="{$package_info.name}|{$package_info.url}"/>
        {else}
      <input id="{$package_info.name|wash}" type="radio" name="eZSetup_site_type" value="{$package_info.name}"/>
	{/if}
    </td>
    <td>
	{if is_set( $package_info.thumbnail_path )}
          <img class="site-type" src={$package_info.thumbnail_path|ezroot} alt="{$package_info.name|wash}" title="{$package_info.summary|wash}" />
	{elseif is_set( $package_info.thumbnail_url )}
          <img class="site-type" src="{$package_info.thumbnail_url}" alt="{$package_info.summary|wash}" title="{$package_info.summary|wash}"/>
	{else}
	  <img class="site-type" src={"design/standard/images/setup/eZ_setup_template_default.png"|ezroot} alt="{$package_info.name|wash}" title="{$package_info.summary|wash}"  />
        {/if}
    </td>
    <td>
        <span style="font-weight: bold">{$package_info.summary}</span>,  ver. {$package_info.version}<br/>
	{$package_info.description}<br/>
	<br/>
	<span style="font-style: italic">Dependencies</span>:<br/>
	{if is_set( $package_info.requires )}
	    {foreach $package_info.requires as $req_name => $req_info}
		{$req_name} ver.{$req_info.version}:
		{if $req_info.status}
		    <span style="color: green">{'Imported'|i18n('design/standard/setup/init')}</span>
		{else}
		    {'Not imported'|i18n('design/standard/setup/init')}
		{/if}
	    <br/>
	    {/foreach}
	{else}
	Unknown.
	{/if}
    </td>
    <td valign="top">
	{if $package_info.status}
	    <span style="color: green">{'Imported'|i18n('design/standard/setup/init')}</span>
	{else}
	    {'Not imported'|i18n('design/standard/setup/init')}
	{/if}
    </td>
    </tr>
    {/foreach}
{else} {* !$remote_site_packages *}
<tr><td colspan="4">None.</td></tr>
{/if}
</table>


<div>
  <h2>Upload package:</h2>
  <input class="file" name="PackageBinaryFile" type="file" />
  <input type="submit" name="UploadPackageButton" value="{'Upload'|i18n("design/standard/setup/init")}" />
</div>

  {include uri="design:setup/persistence.tpl"}

  {include uri='design:setup/init/navigation.tpl'}

</form>

