<h1>eZ publish 3 definitions</h1>


<p>
Visit sdk.ez.no for more info on the definitions.
</p>

<h2>Content class</h2>
<p>
In eZ publish you can define your own content classes. This is an object
definition if you like. Some examples of content classes are article, forum,
product and user account.
</p>

<h2>Content class attribute</h2>
<p>
Each class consists of several attributes. The attributes or elements define the
name and behaviour of the class. For example an article content class may
consist of the attributes: title, intro and body. The title could be a string
data type; the intro and body could be XML formatted text.
</p>

<h2>Content object</h2>
<p>
A content object is an instance of a defined content class. The content class
defines the structure of content objects. The content object is the actual
documents/articles etc, which are stored in eZ publishTM.
</p>

<h2>Content object version</h2>
<p>
Each content object can consist in several versions. This is to keep track of
changes and to have the possibility to revert changes in an object.
</p>

<h2>Content object attribute</h2>
<p>
Each content object consists of several attributes. These attributes are defined
by a content class attribute. The content object attribute contains the actual
data
</p>

<h2>What is a class?</h2>
<p>
Content classes define all data types used at a website as articles, products,
forums, folders, users, or tasks. You can also say it is an object.
</p>

<p>
The concepts of classes makes adding new content to the site very easy. Users
can start making new content objects immediately by entering data into templates
that is auto-generated by eZ publish. Adding new attributes to content classes
may be done at any time with no change in code or database required.
Using the content structure, users may easily add new categories and
sub-categories for the site.
</p>

<p>
A content object is an instance of the object class. A <b>Music category</b> is an
instance of the Category class. An article about <b>U2</b> would be an instance of
the Article class. The user <b>Peter</b> is an instance of the User class.
Each content object can consist in several versions. This is to keep track of
changes and to have the possibility to revert changes in an object. The
picture to the right shows the creation of a new article using the default
template.
</p>

<p>
The content object structure is the tree structure representation of all the
content on your site. Any node in the tree is a content class instance - a
content object. A content object always has a primary parent node, but may also
be attached to several other nodes. There is no limit on number of levels in the
object structure tree.
</p>


<h2>How to make an object</h2>
<p>
Making or editing objects in eZ publish 3 is made to be simple and fast.
It is all done in the admin interface. When you click the <b>Contents</b> button you
will find a button called <b>new</b>. To the right of this button you will find a
drop down menu consisting of different object possibilities. Folder, article,
picture etc. When you highlight of these and click <b>new</b> you will get into the
<b>Edit</b> window. When you have saved, published, translated, versioned this object
you have made an object.
</p>

<p>
You will find more info on this in the <b>User manuals</b>
</p>

