<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "shop_blue",
                     "development" => false,
                     "summary" => "Blue CSS design for shop",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => "sitestyle",
                     "extension" => false,
                     "is_installed" => false,
                     "is_active" => true,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "3.3.0-1",
                                           "named-version" => "3.3 beta 1" ),
                     "maintainers" => array(),
                     "packaging" => array( "timestamp" => "1069863984",
                                           "host" => "jb.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1069863985" ) ),
                     "groups" => array(),
                     "changelog" => array(),
                     "file-list" => array( "default" => array( array( "name" => "shop-blue.css",
                                                                      "subdirectory" => "design/shop/stylesheets",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "cssfile",
                                                                      "path" => "design/shop/stylesheets/shop-blue.css",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069863986",
                                                                      "md5" => "a88b2aaf419b8b8dc5620a0ade1c04fe" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "design/shop/images/shop-blue.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069863986",
                                                                      "md5" => "7de287ec60c12b297c142b2781043d61" ),
                                                               array( "name" => "tab_corner-top_left.gif",
                                                                      "subdirectory" => "design/shop/images/blue",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/shop/images/blue/tab_corner-top_left.gif",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069863987",
                                                                      "md5" => "b85ca53219be195cd5cb82b91bd86549" ),
                                                               array( "name" => "tab_corner-top_right.gif",
                                                                      "subdirectory" => "design/shop/images/blue",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/shop/images/blue/tab_corner-top_right.gif",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069863987",
                                                                      "md5" => "17206c03c5a25894639c8b7ad970367d" ),
                                                               array( "name" => "shopping-menu-icon.gif",
                                                                      "subdirectory" => "design/shop/images",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/shop/images/shopping-menu-icon.gif",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => true,
                                                                      "modified" => 1069863987,
                                                                      "md5" => "7d777e2f25c8673bb199defd8c37ee5f" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1069863986" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1069863986",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1069863986",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1069863984",
                             "summary" => "1069863984",
                             "type" => "1069863985",
                             "version-number" => "1069863985",
                             "release-number" => "1069863985",
                             "licence" => "1069863985",
                             "state" => "1069863985" );
$InstallData = array();
$RepositoryPath = "var/shop/storage/packages";
?>
