{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h3>{$result_number}. {"Missing DOM extension"|i18n("design/standard/setup/tests")}</h3>
<p>
 {"The DOM extension is not available to eZ Publish. Without it eZ Publish will not work."|i18n("design/standard/setup/tests")}
</p>
<p>
 {'In most cases, the DOM extension is enabled by default because it is included in the PHP core. However, some Linux distributions have PHP without compiled-in support for DOM. Instead, they provide DOM as a shared module in a separate RPM package called "php-xml".'|i18n("design/standard/setup/tests")}
</p>