{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h3>{$result_number}. {"Missing iconv extension"|i18n("design/standard/setup/tests")}</h3>
<p>
 {"The iconv extension is not available to eZ Publish. Without it eZ Publish will not work."|i18n("design/standard/setup/tests")}
</p>
<p>
 {'In most cases, the iconv extension is enabled by default because it is included in the PHP core. However, some Linux distributions have PHP without compiled-in support for iconv. Instead, they provide iconv as a shared module in a separate RPM package called "php-iconv" (or "php5-iconv").'|i18n("design/standard/setup/tests")}
</p>
