{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h3>{$result_number}. {"Missing intl extension"|i18n("design/standard/setup/tests")}</h3>
<p>
    {"The intl extension, required for internationalization, is not installed or enabled."|i18n("design/standard/setup/tests")}
</p>
<p>
    {"More information on installing it is available at"|i18n("design/standard/setup/tests")} <a target="_other" href="http://php.net/intl.installation.php">php.net</a>.
</p>
