{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h3>{$result_number}. {"Missing text creation functions"|i18n("design/standard/setup/tests")}</h3>
<p>
    {"The PHP functions ImageTTFText and ImageTTFBBox is missing. Without these functions it is not possible to use the texttoimage template operator."|i18n("design/standard/setup/tests")}
</p>
<p>
 {"To enable these functions you need to recompile PHP with support for it, more information on that subject is available at"|i18n("design/standard/setup/tests")} <a target="_other" href="http://www.php.net/manual/en/ref.image.php">php.net</a>.
</p>
