{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h3>{$result_number}. {"Time zone configuration"|i18n("design/standard/setup/tests")}</h3>
<p>{"You are using the default time zone, UTC. It is important that you set your time zone to make sure date and time is handled correctly. To do this, set the <strong>date.timezone</strong> setting in <strong>php.ini</strong>."|i18n("design/standard/setup/tests")}
</p>

<p>{"Example <strong>php.ini</strong> configuration:"|i18n("design/standard/setup/tests")}</p>
<pre class="example">date.timezone = "Europe/Oslo"</pre>

<p>{'For a list of valid time zones see the <a href="http://php.net/timezones">List of Supported Time zones</a> in the PHP documentation.'|i18n("design/standard/setup/tests")}</p>

<p>{'Alternatively, if you do not have access to modify <strong>php.ini</strong>, you can change the time zone in <strong>config.php</strong>. Time zone set in <strong>config.php</strong> will override the <strong>php.ini</strong> time zone setting.'|i18n("design/standard/setup/tests")}

<p>{"Example <strong>config.php</strong> configuration:"|i18n("design/standard/setup/tests")}</p>
<pre class="example">&lt;?php <br />date_default_timezone_set( "Europe/Oslo" ); <br />?&gt;</pre>        

<p>{'If you want to keep UTC as your time zone, check <strong>Ignore this test</strong> below to proceed.'|i18n("design/standard/setup/tests")}</p>

