{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h3>{$result_number}. {"PHP does not register environment variables"|i18n("design/standard/setup/tests")}</h3>
<p>
{"PHP is currently not configured to register environment variables in the global variable $_ENV."|i18n("design/standard/setup/tests")}
{"Since some extensions might use $_ENV it is recommended to fix it unless you have full control over all extensions you use!"|i18n("design/standard/setup/tests")}
</p>
<p>
{"To fix this, edit your php.ini configuration and add E to the variables_order setting and restart your webserver."|i18n("design/standard/setup/tests")}
</p>