{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="ajaxuploader-preview">
    <dl>
    {foreach $node.data_map as $attribute}
        {if $attribute.has_content}
            <dt>{$attribute.contentclass_attribute_name|wash()}</dt>
            <dd>{attribute_view_gui attribute=$attribute}</dd>
        {/if}
    {/foreach}
    </dl>
</div>
