
START:

INC START:
current in inc:var in inc_ns namespace
root in inc:var in root of inc
specific ns in inc:var in inc_ns namespace
global in inc:global
global with ns in inc:in first_ns namespace
INC END:

INC START:
current in inc:var in inc_ns namespace
root in inc:var in root of inc
specific ns in inc:var in inc_ns namespace
global in inc:global
global with ns in inc:in first_ns namespace
INC END:

END:
