Full:
Name: New article

Edit gui:
Title:
eZString

Message:
eZText

Author:
eZString

Author2:
eZString

------------------------------

View gui:
*Title*
Viewing eZString(abc)(Title): New article
-------------------------------
*Message*
eZText: Input your value
-------------------------------
*Author*
eZString: Input your value
-------------------------------
*Author2*
Viewing eZString(abc)(Author2): Arne

Children:
Name: Sub article
================================
Folder: Sub folder

Line:
Name: New article
