Full:
Name: New article

Edit gui:
Title:
eZString

Message:
eZText

Author:
eZString

Author2:
eZString

File:
eZFile

------------------------------

View gui:
*Title*
Viewing overridden eZString(Title): New article
-------------------------------
*Message*
eZText: Input your value
-------------------------------
*Author*
eZString: Input your value
-------------------------------
*Author2*
Viewing overridden eZString(Author2): Arne
-------------------------------
*File*
Viewing overridden eZFile(File): info.pdf

Children:
Name: Sub article
================================
Folder: Sub folder

Line:
Name: New article

List item:
Folder item: New article

Viewing overridden eZFile(Title): New article
