
$lookup[$number]($number)               =Two(2)

$lookup.item[$number.item]($number.item)=Two(2)

$lookup[$number]($number)               =Three(3)

$lookup.item[$number.item]($number.item)=Three(3)

$lookup[$number]($number)               =Five(5)

$lookup.item[$number.item]($number.item)=Five(5)

$lookup[$number]($number)               =Ten(10)

$lookup.item[$number.item]($number.item)=Ten(10)

$lookup[$number]($number)               =II(2)

$lookup.item[$number.item]($number.item)=II(2)

$lookup[$number]($number)               =III(3)

$lookup.item[$number.item]($number.item)=III(3)

$lookup[$number]($number)               =V(5)

$lookup.item[$number.item]($number.item)=V(5)

$lookup[$number]($number)               =X(10)

$lookup.item[$number.item]($number.item)=X(10)
