Loop eight times: a to h
0,1,0: a
1,2,1: b
2,3,2: c
3,4,3: d
4,5,4: e
5,6,5: f
6,7,6: g
7,8,7: h
------------------------------------
Loop eight times, offset 2: c to h
2,1,0: c
3,2,1: d
4,3,2: e
5,4,3: f
6,5,4: g
7,6,5: h
------------------------------------
Loop eight times reverse, offset 2: f to a
5,1,0: f
4,2,1: e
3,3,2: d
2,4,3: c
1,5,4: b
0,6,5: a

====================================

Loop eight times, offset 2, max 5: c to g
2,1,0: c
3,2,1: d
4,3,2: e
5,4,3: f
6,5,4: g
------------------------------------
Loop eight times reverse, offset 2, max 5: f to b
5,1,0: f
4,2,1: e
3,3,2: d
2,4,3: c
1,5,4: b

====================================

Loop eight times, offset 2, max 5: c to h, skip d
2,1,0: c
4,2,1: e
5,3,2: f
6,4,3: g
7,5,4: h
------------------------------------
Loop eight times reverse, offset 2, max 5: f to a, skip d
5,1,0: f
4,2,1: e
2,3,2: c
1,4,3: b
0,5,4: a
