-----------
===========
    Match 9
===========
-----------

--------------------------

=====
switch test in let loop: 1
=====
========
   - switcher=5
========
=====
switch test in let loop: 2
=====
========
   - switcher=6
========
=====
switch test in let loop: 3
=====
========
   - switcher=7
========
=====
switch test in let loop: 4
=============
   - switcher is greater than 7 (to be precise: 8)
===================
      - switcher match 8( going to check loop )
===========
================ List
                - 1
                - 2
                - 3
                - 4
                - 5
================
=====
switch test in let loop: 5
=============
   - switcher is greater than 7 (to be precise: 9)
===================
      - switcher match 9
===========