This one does match.
match : derick
=========================================================
This one does match.
amos
=========================================================
Not this one either.
We were trying to find bård
=========================================================
Match : 2
=========================================================
First(2):
In array
Second():
Not in array
=========================================================
Var: 1
Default case match:
Default case: 1
Empty default case match:
Empty default case with space match:
