i=5
i=4
i=3
i=2
i=1
===============================================================
===============================================================
1 :: 2 ::  :: 4 :: 6 :: 7
===============================================================
One more dark beer, please.
One more light beer, please.
One more white beer, please.
One more dark beer, please.
One more light beer, please.
One more white beer, please.
One more dark beer, please.
