<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "intranet_red",
                     "development" => false,
                     "summary" => "Red CSS design for intranet",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => "sitestyle",
                     "extension" => false,
                     "is_installed" => false,
                     "is_active" => true,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "3.3.0-1",
                                           "named-version" => "3.3 beta 1" ),
                     "maintainers" => array(),
                     "packaging" => array( "timestamp" => "1069864030",
                                           "host" => "jb.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1069864030" ) ),
                     "groups" => array(),
                     "changelog" => array(),
                     "file-list" => array( "default" => array( array( "name" => "intranet_red.css",
                                                                      "subdirectory" => "design/intranet/stylesheets",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "cssfile",
                                                                      "path" => "design/intranet/stylesheets/intranet_red.css",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864030",
                                                                      "md5" => "618f53349ae9148e525870dd178f0561" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "design/intranet/images/intranet_red.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864031",
                                                                      "md5" => "d8c83a41a5344752f799569d9c6f62a8" ),
                                                               array( "name" => "green_logo.png",
                                                                      "subdirectory" => "design/intranet/images",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/intranet/images/green_logo.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => true,
                                                                      "modified" => 1069864031,
                                                                      "md5" => "2d085abce3dec88d01a9b34fc02c4a66" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1069864030" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1069864030",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1069864030",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1069864030",
                             "summary" => "1069864030",
                             "type" => "1069864030",
                             "version-number" => "1069864030",
                             "release-number" => "1069864030",
                             "licence" => "1069864030",
                             "state" => "1069864030" );
$InstallData = array();
$RepositoryPath = "var/intranet/storage/packages";
?>
