{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="toollist">
    <div class="toollist-design">
    <h2>{$text}</h2>
        <div class="content-view-children">
            <a href={$href}>{$text}</a>
        </div>
    </div>
</div>