{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="toolbar-item {$placement}">
    <div class="toolbox">
        <div class="toolbox-design">
        {if $current_user.is_logged_in}
            <h2>{'Account'|i18n( 'design/standard/toolbar' )}</h2>
        {else}
            <h2>{'Not logged in'|i18n( 'design/standard/toolbar' )}</h2>
        {/if}

        <div class="toolbox-content">
        {if $current_user.is_logged_in}
        <div class="info-text">
            <p>
            {'Logged in as: %username'|i18n( 'design/standard/toolbar',, hash( '%username', $current_user.contentobject.name|wash ) )}
            </p>
        </div>
        <div class="content-link">
            <p>
            <a href={concat("/content/edit/", $current_user.contentobject_id, "/")|ezurl}>{'Edit account'|i18n( 'design/standard/toolbar' )}</a>
            </p>
        </div>
        <div class="content-link">
            <p>
            <a href={"/user/password"|ezurl}>{'Change password'|i18n( 'design/standard/toolbar' )}</a>
            </p>
        </div>
        <div class="content-link">
            <p>
            <a href={"/user/logout"|ezurl}>{'Logout'|i18n( 'design/standard/toolbar' )}</a>
            </p>
        </div>
        {else}
        <form method="post" action={"/user/login/"|ezurl}>
        <div class="info-text">
            <label for="id1">{"Username"|i18n( 'design/standard/toolbar' )}</label>
            <input class="textinput" type="text" size="10" name="Login" id="id1" value="{$User:login|wash}" />
        </div>

        <div class="info-text">
            <label for="id2">{"Password"|i18n( 'design/standard/toolbar' )}</label>
            <input class="textinput" type="password" size="10" name="Password" id="id2" value="" />
        </div>

        <input type="image" class="searchimage" src={"1x1.gif"|ezimage} />
        <div class="content-link">
            <p>
                <a href={"/user/register"|ezurl}>{'Not registered?'|i18n( 'design/standard/toolbar' )}</a>
            </p>
        </div>
        <div class="content-link">
            <p>
            <a href={"/user/forgotpassword"|ezurl}>{'Forgot your password?'|i18n( 'design/standard/toolbar' )}</a>
            </p>
        </div>
        </form>
        {/if}
        </div>

        </div>
    </div>
</div>
