{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="toolbar-item {$placement}">
    <div class="toolbox">
    <div class="toolbox-design">

    {def $currency_list = fetch( 'shop', 'currency_list', hash( 'status', 'active' ) )
         $preferred_currency_code = fetch( 'shop', 'preferred_currency_code' )}
        <h2>{"Preferred currency"|i18n("design/standard/toolbar")}</h2>
        <div class="toolbox-content">
        {if count( $currency_list )}
            <form action={'shop/setpreferredcurrency'|ezurl} method="post">
                <select name="Currency" title="Select currency">
                    {foreach $currency_list as $Currency}
                        <option value="{$Currency.code}" {if eq( $Currency.code, $preferred_currency_code )}selected="selected"{/if}>{$Currency.code}</option>
                    {/foreach}
                </select>
                {* Set button *}
                <input class="button" type="submit" name="SetButton" value="{'Set'|i18n( 'design/standard/toolbar' )}" title="{'Set the selected currency as preferred.'|i18n( 'design/standard/toolbar' )}" />
            </form>
        {else}
            <p>{"There are no available currencies"|i18n("design/standard/toolbar")}</p>
        {/if}
        </div>
    {undef}

    </div>
    </div>
</div>