{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=utf8?*}
<!DOCTYPE html>
<html lang="{$site.http_equiv.Content-language|wash}">

<head>

{ezcss_load( array(
    'core.css',
    ezini( 'StylesheetSettings', 'CSSFileList', 'design.ini' )
) )}

{ezscript_load( array(
    ezini( 'JavaScriptSettings', 'JavaScriptList', 'design.ini' )
) )}

{include uri="design:page_head.tpl" enable_print=false()}
</head>

<body>

{* Main area START *}

{include uri="design:page_mainarea.tpl"}

{* Main area END *}

{include uri="design:page_copyright.tpl"}

<!--DEBUG_REPORT-->

</body>
</html>
