<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "forum_red",
                     "development" => false,
                     "summary" => "Red CSS design for forum",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => "sitestyle",
                     "extension" => false,
                     "is_installed" => false,
                     "is_active" => true,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "3.3.0-1",
                                           "named-version" => "3.3 beta 1" ),
                     "maintainers" => array(),
                     "packaging" => array( "timestamp" => "1069864046",
                                           "host" => "jb.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1069864046" ) ),
                     "groups" => array(),
                     "changelog" => array(),
                     "file-list" => array( "default" => array( array( "name" => "forum.css",
                                                                      "subdirectory" => "design/forum/stylesheets",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "cssfile",
                                                                      "path" => "design/forum/stylesheets/forum.css",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864047",
                                                                      "md5" => "4f0ddda9a664c2d563477584738343ef" ),
                                                               array( "name" => "forum_header-red.gif",
                                                                      "subdirectory" => "design/forum/images",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "image",
                                                                      "path" => "design/forum/images/forum_header-red.gif",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864047",
                                                                      "md5" => "9d37f00f3c3ed53a809a8d3ca0bb0ec4" ),
                                                               array( "name" => "thumbnail.jpg",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "design/forum/images/forum_red.jpg",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => true,
                                                                      "modified" => 1069864047,
                                                                      "md5" => "833136502168d88c58d705c955935770" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1069864047" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1069864047",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1069864047",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1069864046",
                             "summary" => "1069864046",
                             "type" => "1069864046",
                             "version-number" => "1069864046",
                             "release-number" => "1069864046",
                             "licence" => "1069864046",
                             "state" => "1069864046" );
$InstallData = array();
$RepositoryPath = "var/forum/storage/packages";
?>
