{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $attribute.has_content}
{$attribute.content.value|wash( xhtml )}
{else}
{'Not specified'|i18n( 'design/standard/content/datatype' )}
{/if}