{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
<label>{'Option set name'|i18n( 'design/standard/content/datatype' )}:</label>
{$attribute.content.name|wash}
</div>

{foreach $attribute.content.multioption_list as $Multioptions}
<div class="block">
<label>{$Multioptions.name|wash}:</label>
<select name="eZOption[{$attribute.id}][]">
    {section var=Option loop=$Multioptions.optionlist}
            {if ne( $Option.item.additional_price, '' )}
                {if eq( sum( $Option.index, 1 ), $Multioptions.default_option_id )}
                    <option value="{$Option.item.option_id}" selected="selected">{$Option.item.value|wash}-{$Option.item.additional_price|l10n( currency )}</option>
                {else}
                    <option value="{$Option.item.option_id}">{$Option.item.value|wash}-{$Option.item.additional_price|l10n( currency )}</option>
                {/if}
            {else}
                {if eq(sum($Option.index,1), $Multioptions.default_option_id)}
                    <option value="{$Option.item.option_id}" selected="selected">{$Option.item.value|wash}</option>
                {else}
                    <option value="{$Option.item.option_id}">{$Option.item.value|wash}</option>
                {/if}
            {/if}
        {/section}
    </select>
</div>
{/foreach}