{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form method="post" action={"/setup/session/"|ezurl}>

<h1>{"Session admin"|i18n("design/standard/setup")}</h1>

{section show=$sessions_removed}
<div class="feedback">
{"The sessions were successfully removed."|i18n("design/standard/setup")}
</div>
{/section}

<div class="objectheader">
<h2>{"Session entries"|i18n("design/standard/setup")}</h2>
</div>

<div class="object">
    <p>{"Number of active sessions"|i18n("design/standard/setup")}: {$sessions_active}</p><br />
    <p>{"Use the buttons below to delete the session entries that are present in the database."|i18n("design/standard/setup")}<br />
       {"WARNING! When removing sessions, users that are logged in will be thrown out from the system."|i18n("design/standard/setup")}</p>
<br />
<input type="submit" name="RemoveAllSessionsButton" value="{"Remove all sessions"|i18n("design/standard/setup")}" />
<br />
<br />
<input type="submit" name="RemoveTimedOutSessionsButton" value="{"Remove timed out / old sessions"|i18n("design/standard/setup")}" />

</form>
