{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="context-block">

<h1>{"Session admin"|i18n( "design/standard/setup/session" )}</h1>

<div class="message-feedback">
    <h2><span class="time">[{currentdate()|l10n( shortdatetime )}]</span> {"Your current session handler does not support session administration."|i18n( "design/standard/setup/session" )}</h2>
</div>

</div>
