{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $check_visibility = ezini( 'SiteAccessSettings', 'ShowHiddenNodes' )|ne( 'true' )
     $content = false()}
{section name=Relation loop=$attribute.content.relation_list}
    {set $content = fetch(
        content, object,
        hash(
            object_id, $:item.contentobject_id,
            object_version,$:item.contentobject_version
        )
    )}
    {if or( $content.can_read, $content.can_view_embed)}
        {if or(
            $check_visibility|not,
            fetch( content, node, hash( node_id, $Relations.item.node_id ) ).is_invisible|not
        )}
            {content_pdf_gui view=embed content_object=$content}
        {/if}
    {/if}
{/section}
{undef $check_visibility $content}
