{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="maincontentheader">
    <h1>
        {"Choose parent node"|i18n("design/standard/package/installers/ezcontentobject")}
    </h1>
</div>

<p>
    {"Select parent node for new node."|i18n("design/standard/package/installers/ezcontentobject")}
</p>
