{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="package" class="create">
    <div id="sid-{$current_step.id|wash}" class="pc-{$installer.type|wash}">

    <form method="post" action={'package/install'|ezurl}>

    {include uri="design:package/install/error.tpl"}

    {include uri="design:package/install_header.tpl"}

    <p>{'Please select where you want to place the imported items.'|i18n('design/standard/package')}</p>


    <label>{'If you want to change the placement click the browse button.'|i18n('design/standard/package')}</label>

    {section loop=$top_nodes_map}
    <div class="block">
    {if $:item.new_node_id}
        {let class=fetch( content, node, hash( node_id, $:item.new_node_id ) ).object.content_class}
        {'Place %object_name in node %node_placement'|i18n( 'design/standard/package',, hash( '%object_name', concat( '<i>', $:item.name, '</i>' ), '%node_placement', concat( $:class.identifier|class_icon( small, $:class.name ), ' ', $:item.new_parent_name ) ) )}
        {/let}
    {else}
        {'Choose placement for %object_name'|i18n( 'design/standard/package',, hash( '%object_name', $:item.name ) )}
    {/if}
        &nbsp;<input class="button" type="submit" Name="{concat('BrowseNode_', $:item.old_node_id)}" value="{"Browse"|i18n("design/standard/package")}" />
      </div>
    {/section}

    {include uri="design:package/navigator.tpl"}

    </form>

    </div>
</div>