custom,%Y-%m-%d:
      '2004-02-23'
custom,klokka %H:%i:%s:
      'klokka 16:12:55'
custom,%B %r %S %a %A %d %D %F %g %G %h %H %i %I %j %l %L %m %M %n %s %t %w %W %Y %y %z:
      '%B %r %S pm PM 23 Mon February 4 16 04 16 12 0 23 Monday 1 02 Feb 2 55 29 1 09 2004 04 53'
custom,abcdefghijklmnopqrstuvwxyz-ABCDEFGHIJKLMNOPQRSTUVWXYZ-1234567890:
      'abcdefghijklmnopqrstuvwxyz-ABCDEFGHIJKLMNOPQRSTUVWXYZ-1234567890'
