Input: static, offset=static, length=static
3456
34
56
123
456
===============================================
Input: non-static, offset=static, length=static
3456
34
56
123
456
===============================================
Input: non-static, offset=non-static, length=static
3456
34
56
123
456
===============================================
Input: non-static, offset=non-static, length=non-static
3456
34
56
123
456
===============================================
