{let arr=array( 1, 2) true=true() false=false() string="abc" integer=4 double=4.2}
$arr|is_array='{$arr|is_array}'
$arr|is_boolean='{$arr|is_boolean}'
$arr|is_class( 'testclass1' )='{$arr|is_class( 'testclass1' )}'
$arr|is_float='{$arr|is_float}'
$arr|is_integer='{$arr|is_integer}'
$arr|is_null='{$arr|is_null}'
$arr|is_numeric='{$arr|is_numeric}'
$arr|is_object='{$arr|is_object}'
is_set( $arr )='{is_set( $arr )}'
$arr|is_string='{$arr|is_string}'
is_unset( $arr )='{is_unset( $arr )}'
$arr|get_type='{$arr|get_type}'

$true|is_array='{$true|is_array}'
$true|is_boolean='{$true|is_boolean}'
$true|is_class( 'testclass1' )='{$true|is_class( 'testclass1' )}'
$true|is_float='{$true|is_float}'
$true|is_integer='{$true|is_integer}'
$true|is_null='{$true|is_null}'
$true|is_numeric='{$true|is_numeric}'
$true|is_object='{$true|is_object}'
is_set( $true )='{is_set( $true )}'
$true|is_string='{$true|is_string}'
is_unset( $true )='{is_unset( $true )}'
$true|get_type='{$true|get_type}'

$false|is_array='{$false|is_array}'
$false|is_boolean='{$false|is_boolean}'
$false|is_class( 'testclass1' )='{$false|is_class( 'testclass1' )}'
$false|is_float='{$false|is_float}'
$false|is_integer='{$false|is_integer}'
$false|is_null='{$false|is_null}'
$false|is_numeric='{$false|is_numeric}'
$false|is_object='{$false|is_object}'
is_set( $false )='{is_set( $false )}'
$false|is_string='{$false|is_string}'
is_unset( $false )='{is_unset( $false )}'
$false|get_type='{$false|get_type}'

$string|is_array='{$string|is_array}'
$string|is_boolean='{$string|is_boolean}'
$string|is_class( 'testclass1' )='{$string|is_class( 'testclass1' )}'
$string|is_float='{$string|is_float}'
$string|is_integer='{$string|is_integer}'
$string|is_null='{$string|is_null}'
$string|is_numeric='{$string|is_numeric}'
$string|is_object='{$string|is_object}'
is_set( $string )='{is_set( $string )}'
$string|is_string='{$string|is_string}'
is_unset( $string )='{is_unset( $string )}'
$string|get_type='{$string|get_type}'

$integer|is_array='{$integer|is_array}'
$integer|is_boolean='{$integer|is_boolean}'
$integer|is_class( 'testclass1' )='{$integer|is_class( 'testclass1' )}'
$integer|is_float='{$integer|is_float}'
$integer|is_integer='{$integer|is_integer}'
$integer|is_null='{$integer|is_null}'
$integer|is_numeric='{$integer|is_numeric}'
$integer|is_object='{$integer|is_object}'
is_set( $integer )='{is_set( $integer )}'
$integer|is_string='{$integer|is_string}'
is_unset( $integer )='{is_unset( $integer )}'
$integer|get_type='{$integer|get_type}'

$double|is_array='{$double|is_array}'
$double|is_boolean='{$double|is_boolean}'
$double|is_class( 'testclass1' )='{$double|is_class( 'testclass1' )}'
$double|is_float='{$double|is_float}'
$double|is_integer='{$double|is_integer}'
$double|is_null='{$double|is_null}'
$double|is_numeric='{$double|is_numeric}'
$double|is_object='{$double|is_object}'
is_set( $double )='{is_set( $double )}'
$double|is_string='{$double|is_string}'
is_unset( $double )='{is_unset( $double )}'
$double|get_type='{$double|get_type}'

$object1|is_array='{$object1|is_array}'
$object1|is_boolean='{$object1|is_boolean}'
$object1|is_class( 'testclass1' )='{$object1|is_class( 'testclass1' )}'
$object1|is_float='{$object1|is_float}'
$object1|is_integer='{$object1|is_integer}'
$object1|is_null='{$object1|is_null}'
$object1|is_numeric='{$object1|is_numeric}'
$object1|is_object='{$object1|is_object}'
is_set( $object1 )='{is_set( $object1 )}'
$object1|is_string='{$object1|is_string}'
is_unset( $object1 )='{is_unset( $object1 )}'
$object1|get_type='{$object1|get_type}'

$object2|is_array='{$object2|is_array}'
$object2|is_boolean='{$object2|is_boolean}'
$object2|is_class( 'testclass1' )='{$object2|is_class( 'testclass1' )}'
$object2|is_float='{$object2|is_float}'
$object2|is_integer='{$object2|is_integer}'
$object2|is_null='{$object2|is_null}'
$object2|is_numeric='{$object2|is_numeric}'
$object2|is_object='{$object2|is_object}'
is_set( $object2 )='{is_set( $object2 )}'
$object2|is_string='{$object2|is_string}'
is_unset( $object2 )='{is_unset( $object2 )}'
$object2|get_type='{$object2|get_type}'

$object1|get_class='{$object1|get_class}'
$object2|get_class='{$object2|get_class}'

----------------------------------------

is_array( $arr )='{is_array( $arr )}'
is_boolean( $arr )='{is_boolean( $arr )}'
is_float( $arr )='{is_float( $arr )}'
is_integer( $arr )='{is_integer( $arr )}'
is_null( $arr )='{is_null( $arr )}'
is_numeric( $arr )='{is_numeric( $arr )}'
is_object( $arr )='{is_object( $arr )}'
is_set( $arr )='{is_set( $arr )}'
is_string( $arr )='{is_string( $arr )}'
is_unset( $arr )='{is_unset( $arr )}'
get_type( $arr )='{get_type( $arr )}'

is_array( $true )='{is_array( $true )}'
is_boolean( $true )='{is_boolean( $true )}'
is_float( $true )='{is_float( $true )}'
is_integer( $true )='{is_integer( $true )}'
is_null( $true )='{is_null( $true )}'
is_numeric( $true )='{is_numeric( $true )}'
is_object( $true )='{is_object( $true )}'
is_set( $true )='{is_set( $true )}'
is_string( $true )='{is_string( $true )}'
is_unset( $true )='{is_unset( $true )}'
get_type( $true )='{get_type( $true )}'

is_array( $false )='{is_array( $false )}'
is_boolean( $false )='{is_boolean( $false )}'
is_float( $false )='{is_float( $false )}'
is_integer( $false )='{is_integer( $false )}'
is_null( $false )='{is_null( $false )}'
is_numeric( $false )='{is_numeric( $false )}'
is_object( $false )='{is_object( $false )}'
is_set( $false )='{is_set( $false )}'
is_string( $false )='{is_string( $false )}'
is_unset( $false )='{is_unset( $false )}'
get_type( $false )='{get_type( $false )}'

is_array( $string )='{is_array( $string )}'
is_boolean( $string )='{is_boolean( $string )}'
is_float( $string )='{is_float( $string )}'
is_integer( $string )='{is_integer( $string )}'
is_null( $string )='{is_null( $string )}'
is_numeric( $string )='{is_numeric( $string )}'
is_object( $string )='{is_object( $string )}'
is_set( $string )='{is_set( $string )}'
is_string( $string )='{is_string( $string )}'
is_unset( $string )='{is_unset( $string )}'
get_type( $string )='{get_type( $string )}'

is_array( $integer )='{is_array( $integer )}'
is_boolean( $integer )='{is_boolean( $integer )}'
is_float( $integer )='{is_float( $integer )}'
is_integer( $integer )='{is_integer( $integer )}'
is_null( $integer )='{is_null( $integer )}'
is_numeric( $integer )='{is_numeric( $integer )}'
is_object( $integer )='{is_object( $integer )}'
is_set( $integer )='{is_set( $integer )}'
is_string( $integer )='{is_string( $integer )}'
is_unset( $integer )='{is_unset( $integer )}'
get_type( $integer )='{get_type( $integer )}'

is_array( $double )='{is_array( $double )}'
is_boolean( $double )='{is_boolean( $double )}'
is_float( $double )='{is_float( $double )}'
is_integer( $double )='{is_integer( $double )}'
is_null( $double )='{is_null( $double )}'
is_numeric( $double )='{is_numeric( $double )}'
is_object( $double )='{is_object( $double )}'
is_set( $double )='{is_set( $double )}'
is_string( $double )='{is_string( $double )}'
is_unset( $double )='{is_unset( $double )}'
get_type( $double )='{get_type( $double )}'

is_array( $object1 )='{is_array( $object1 )}'
is_boolean( $object1 )='{is_boolean( $object1 )}'
is_float( $object1 )='{is_float( $object1 )}'
is_integer( $object1 )='{is_integer( $object1 )}'
is_null( $object1 )='{is_null( $object1 )}'
is_numeric( $object1 )='{is_numeric( $object1 )}'
is_object( $object1 )='{is_object( $object1 )}'
is_set( $object1 )='{is_set( $object1 )}'
is_string( $object1 )='{is_string( $object1 )}'
is_unset( $object1 )='{is_unset( $object1 )}'
get_type( $object1 )='{get_type( $object1 )}'

is_array( $object2 )='{is_array( $object2 )}'
is_boolean( $object2 )='{is_boolean( $object2 )}'
is_float( $object2 )='{is_float( $object2 )}'
is_integer( $object2 )='{is_integer( $object2 )}'
is_null( $object2 )='{is_null( $object2 )}'
is_numeric( $object2 )='{is_numeric( $object2 )}'
is_object( $object2 )='{is_object( $object2 )}'
is_set( $object2 )='{is_set( $object2 )}'
is_string( $object2 )='{is_string( $object2 )}'
is_unset( $object2 )='{is_unset( $object2 )}'
get_type( $object2 )='{get_type( $object2 )}'

get_class( $object1 )='{get_class( $object1 )}'
get_class( $object2 )='{get_class( $object2 )}'

{/let}