Static optimization tests:
expr5.1:or( false(), 5 )='5'
expr1:and( false(), $value )=''
expr2:and( $value, false() )=''
expr3:and( true(), true() )='1'
expr4:and( true(), $value )=''
expr5:or( true(), $value )='1'
expr6:or( false(), true(), $value )='1'
expr7:or( $value, false() )=''
expr8:or( false(), $value )=''
expr9:or( false(), false() )=''

1|lt( 0 )=''
0|lt( 0 )=''
0|lt( 1 )='1'

1|gt( 0 )='1'
0|gt( 0 )=''
0|gt( 1 )=''

1|le( 0 )=''
0|le( 0 )='1'
0|le( 1 )='1'

1|ge( 0 )='1'
0|ge( 0 )='1'
0|ge( 1 )=''

and( 0, 0, 0, 0 )=''
and( 1, $value, 1, 1 )=''
and( 1, 1, 1, 1 )='1'

or( 0, 0, 0, 0 )=''
or( 1, 0, 1, 1 )='1'
or( 1, 1, 1, 1 )='1'

eq( 0, 0 )='1'
eq( 1, 1 )='1'
eq( 0, $value )='1'
eq( 1, $value )=''

ne( 0, 0 )=''
ne( 1, 1 )=''
ne( 0, $value )=''
ne( 1, $value )='1'

not( 1 )=''
not( $value )='1'
$bool|not|choose( 'false', 'true' )='false'
$bool2|not|choose( 'false', 'true' )='true'
$bool3|not|choose( 'false', 'true' )='true'
45|not()=''
$value|not()='1'
$value|not|not=''
