text=<img src="/ezpublish-3.4//share/icons/crystal/32x32/mimetypes/ascii.png" width="32" height="32" alt="text/plain" title="text/plain" />
image=<img src="/ezpublish-3.4//share/icons/crystal/32x32/mimetypes/image.png" width="32" height="32" alt="image/jpeg" title="image/jpeg" />
default=<img src="/ezpublish-3.4//share/icons/crystal/32x32/mimetypes/document.png" width="32" height="32" alt="something/somewhere" title="something/somewhere" />
