{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="warning">
<h2>{"Incompatible product type"|i18n("design/standard/error/shop")}</h2>
<p>{"The requested object and current basket have incompatible price datatypes."|i18n("design/standard/error/shop")}</p>
</div>

{section show=$embed_content}
    {$embed_content}
{/section}
