<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "blog_red",
                     "development" => false,
                     "summary" => "Blue CSS design for blog--",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => false,
                     "extension" => false,
                     "is_installed" => false,
                     "is_active" => true,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "3.3.0-1",
                                           "named-version" => "3.3 beta 1" ),
                     "maintainers" => array(),
                     "packaging" => array( "timestamp" => "1069864003",
                                           "host" => "jb.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1069864003" ) ),
                     "groups" => array(),
                     "changelog" => array(),
                     "file-list" => array( "default" => array( array( "name" => "blog_red.css",
                                                                      "subdirectory" => "design/blog/stylesheets",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "cssfile",
                                                                      "path" => "design/blog/stylesheets/blog_red.css",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1069864003",
                                                                      "md5" => "28a444286aebb5d00f4c56786af8492e" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "design/blog/images/blog-red.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => true,
                                                                      "modified" => 1069864004,
                                                                      "md5" => "521f74e07c6ce59769f019952e283363" ) ) ),
                     "version-number" => "set",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1069864003" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1069864003",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1069864003",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1069864003",
                             "summary" => "1069864003",
                             "version-number" => "1069864003",
                             "release-number" => "1069864003",
                             "licence" => "1069864003",
                             "state" => "1069864003" );
$InstallData = array();
$RepositoryPath = "var/blog/storage/packages";
?>
