<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1061114927;

$Parameters = array( "name" => "mysite",
                     "summary" => "Personal homepage",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => false,
                     "extension" => false,
                     "ezpublish" => array( "version" => "3.2.0-1",
                                           "named-version" => "3.2 beta1" ),
                     "maintainers" => array( array( "name" => "Anonymous User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead",
                                                    "modified" => "1061309383" ) ),
                     "packaging" => array( "timestamp" => "1061309383",
                                           "host" => "bf.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1061309383" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1061309383",
                                                  "person" => "Anonymous User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package" ),
                                                  "release" => "1",
                                                  "modified" => "1061309383" ) ),
                     "file-list" => array( "default" => array( array( "name" => false,
                                                                      "subdirectory" => false,
                                                                      "type" => "design",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => false,
                                                                      "path" => false,
                                                                      "file-type" => false,
                                                                      "design" => "mysite",
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309385",
                                                                      "md5" => false ),
                                                               array( "name" => "override.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "mysite",
                                                                      "variable-name" => "user_siteaccess",
                                                                      "path" => "settings/siteaccess/mysite/override.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309386",
                                                                      "md5" => "f94a866731c3302e6c377b03e9590180" ),
                                                               array( "name" => "site.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "mysite",
                                                                      "variable-name" => "user_siteaccess",
                                                                      "path" => "settings/siteaccess/mysite/site.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309387",
                                                                      "md5" => "8c95965f170c834e3ad47450e9492ddc" ),
                                                               array( "name" => "override.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "admin",
                                                                      "variable-name" => "admin_siteaccess",
                                                                      "path" => "settings/siteaccess/admin/override.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309388",
                                                                      "md5" => "50f4805254652ccea3c0191a23ce5c21" ),
                                                               array( "name" => "site.ini.append",
                                                                      "subdirectory" => false,
                                                                      "type" => "ini",
                                                                      "role" => "siteaccess",
                                                                      "role-value" => "admin",
                                                                      "variable-name" => "admin_siteaccess",
                                                                      "path" => "settings/siteaccess/admin/site.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309389",
                                                                      "md5" => "47a0ba3f8010fba23cc881208bf4bfc1" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "role-value" => false,
                                                                      "variable-name" => false,
                                                                      "path" => "mysitethumbnail.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061309393",
                                                                      "md5" => "0e32334be316e854c8c4cceb50163f7a" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1061309385" ) ),
                                              "requires" => array( array( "type" => "ezdb",
                                                                          "name" => "mysql",
                                                                          "value" => false,
                                                                          "modified" => "1061309390" ),
                                                                   array( "type" => "ezdb",
                                                                          "name" => "postgresql",
                                                                          "value" => false,
                                                                          "modified" => "1061309392" ) ),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1061309385",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ),
                                         array( "path" => "packages/mysite.sql",
                                                "database-type" => "mysql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061309390",
                                                "os" => false,
                                                "filename" => "mysite.sql",
                                                "sub-directory" => false ),
                                         array( "path" => "packages/mysite_postgresql.sql",
                                                "database-type" => "postgresql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061309392",
                                                "os" => false,
                                                "filename" => "mysite_postgresql.sql",
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1061309385",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1061309383",
                             "version-number" => "1061309383",
                             "release-number" => "1061309383",
                             "licence" => "1061309383",
                             "state" => "1061309383",
                             "summary" => 1061309394 );
$RepositoryPath = "packages";
?>
