<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1061114927;

$Parameters = array( "name" => "mysite",
                     "summary" => "Personal homepage",
                     "description" => false,
                     "vendor" => false,
                     "priority" => false,
                     "type" => false,
                     "extension" => false,
                     "ezpublish" => array( "version" => "3.2.0-1",
                                           "named-version" => "3.2 pre-alpha" ),
                     "maintainers" => array( array( "name" => "Anonymous User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead",
                                                    "modified" => "1061230676" ) ),
                     "packaging" => array( "timestamp" => "1061230676",
                                           "host" => "bf.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "README",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "audience" => false,
                                                  "modified" => "1061230676" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1061230676",
                                                  "person" => "Anonymous User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package" ),
                                                  "release" => "1",
                                                  "modified" => "1061230676" ) ),
                     "file-list" => array( "default" => array( array( "name" => false,
                                                                      "subdirectory" => false,
                                                                      "type" => "design",
                                                                      "role" => false,
                                                                      "path" => false,
                                                                      "file-type" => false,
                                                                      "design" => "mysite",
                                                                      "copy-file" => false,
                                                                      "modified" => "1061230677",
                                                                      "md5" => false ),
                                                               array( "name" => "override.ini.append",
                                                                      "subdirectory" => "settings/siteaccess/mysite",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "path" => "settings/siteaccess/mysite/override.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061230677",
                                                                      "md5" => "f94a866731c3302e6c377b03e9590180" ),
                                                               array( "name" => "site.ini.append",
                                                                      "subdirectory" => "settings/siteaccess/mysite",
                                                                      "type" => "file",
                                                                      "role" => false,
                                                                      "path" => "settings/siteaccess/mysite/site.ini.append",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061230678",
                                                                      "md5" => "981b7336076ba37b1cb5716c6d7851e0" ),
                                                               array( "name" => "thumbnail.png",
                                                                      "subdirectory" => false,
                                                                      "type" => "thumbnail",
                                                                      "role" => false,
                                                                      "path" => "mysitethumbnail.png",
                                                                      "file-type" => false,
                                                                      "design" => false,
                                                                      "copy-file" => false,
                                                                      "modified" => "1061230681",
                                                                      "md5" => "d734082d5c7adc9d3f4c802fb188353b" ) ) ),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezfile",
                                                                          "name" => "collection",
                                                                          "value" => "default",
                                                                          "modified" => "1061230677" ) ),
                                              "requires" => array( array( "type" => "ezdb",
                                                                          "name" => "mysql",
                                                                          "value" => false,
                                                                          "modified" => "1061230679" ),
                                                                   array( "type" => "ezdb",
                                                                          "name" => "postgresql",
                                                                          "value" => false,
                                                                          "modified" => "1061230679" ),
                                                                   array( "type" => "ezdb",
                                                                          "name" => "postgresql",
                                                                          "value" => false,
                                                                          "modified" => "1061230680" ) ),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "collection" => "default",
                                                "type" => "ezfile",
                                                "name" => false,
                                                "modified" => "1061230677",
                                                "os" => false,
                                                "filename" => false,
                                                "sub-directory" => false ),
                                         array( "path" => "packages/mysite.sql",
                                                "database-type" => "mysql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061230679",
                                                "os" => false,
                                                "filename" => "mysite.sql",
                                                "sub-directory" => false ),
                                         array( "path" => "kernel/sql/postgresql/kernel_schema.sql",
                                                "database-type" => "postgresql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061230679",
                                                "os" => false,
                                                "filename" => "kernel_schema.sql",
                                                "sub-directory" => false ),
                                         array( "path" => "kernel/sql/postgresql/cleandata.sql",
                                                "database-type" => "postgresql",
                                                "type" => "sql",
                                                "name" => false,
                                                "modified" => "1061230680",
                                                "os" => false,
                                                "filename" => "cleandata.sql",
                                                "sub-directory" => false ) ),
                     "uninstall" => array( array( "collection" => "default",
                                                  "type" => "ezfile",
                                                  "name" => false,
                                                  "modified" => "1061230677",
                                                  "os" => false,
                                                  "filename" => false,
                                                  "sub-directory" => false ) ) );
$ModifiedParameters = array( "name" => "1061230676",
                             "version-number" => "1061230676",
                             "release-number" => "1061230676",
                             "licence" => "1061230676",
                             "state" => "1061230676",
                             "summary" => 1061230681 );
$RepositoryPath = "packages";
?>
